"""Pack metadata for ai-compute-chip-magazine graphics. Auto-built; re-run build_pack_data.py."""

from __future__ import annotations

PACK = "ai-compute-chip-magazine"
GRAPHICS_AGENT = "v1"

ARTICLES: list[dict] = [
    {
        "slug": '01-when-nvidia-named-the-gpu',
        "file": '01-when-nvidia-named-the-gpu.md',
        "title": 'When a graphics chip got a new job title',
        "chart": 'graphics_pipeline',
        "anchors": [('Aug 1999', 'GeForce 256 launch; GPU coined'), ('Oct 1999', 'SDR cards ship to retail'), ('2006', 'CUDA names a C-on-GPU platform'), ('now', 'GPU is a class, not a monitor')],
        "photo": 'geforce-256.jpg',
    },
    {
        "slug": '02-voodoo-and-the-card-that-vanished',
        "file": '02-voodoo-and-the-card-that-vanished.md',
        "title": 'The 3D card that taught a generation, then vanished',
        "chart": 'graphics_pipeline',
        "anchors": [('1996', 'The 3D card that taught a generation, then vanished enters public record'), ('1997', 'Architecture or software sequel in trade press'), ('1998', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
        "photo": '3dfx-voodoo2.jpg',
    },
    {
        "slug": '03-ati-radeon-the-other-house',
        "file": '03-ati-radeon-the-other-house.md',
        "title": 'The other house on the board: ATI, then AMD',
        "chart": 'graphics_pipeline',
        "anchors": [('2001', 'The other house on the board: ATI, then AMD enters public record'), ('2002', 'Architecture or software sequel in trade press'), ('2004', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
        "photo": 'ati-radeon-9700-pro.png',
    },
    {
        "slug": '04-shader-algebra-in-a-pixel-pipe',
        "file": '04-shader-algebra-in-a-pixel-pipe.md',
        "title": 'Doing algebra in a pixel pipe',
        "chart": 'shader_stages',
        "anchors": [('2001', 'Doing algebra in a pixel pipe enters public record'), ('2003', 'Architecture or software sequel in trade press'), ('2004', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '05-brook-for-gpus',
        "file": '05-brook-for-gpus.md',
        "title": 'Brook for GPUs: a language for a machine that was still a toy',
        "chart": 'software_stack',
        "anchors": [('2003', 'Brook for GPUs: a language for a machine that was st enters public record'), ('2004', 'Architecture or software sequel in trade press'), ('2006', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '06-ian-buck-walks-into-santa-clara',
        "file": '06-ian-buck-walks-into-santa-clara.md',
        "title": 'Ian Buck walks into Santa Clara',
        "chart": 'software_stack',
        "anchors": [('2004', 'Ian Buck walks into Santa Clara enters public record'), ('2006', 'Architecture or software sequel in trade press'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '07-november-8-2006-cuda-gets-a-name',
        "file": '07-november-8-2006-cuda-gets-a-name.md',
        "title": 'November 8, 2006: CUDA gets a name',
        "chart": 'software_stack',
        "anchors": [('Nov 2006', 'CUDA + GeForce 8800 announced'), ('2007', 'Public CUDA SDK and docs trail'), ('2012', 'Consumer cards in ImageNet training'), ('now', 'Platform habit outlives any one chip')],
        "photo": 'geforce-8800-gtx-board.jpg',
    },
    {
        "slug": '08-g80-the-unified-shader',
        "file": '08-g80-the-unified-shader.md',
        "title": 'G80: the unified shader that made compute possible',
        "chart": 'unified_shader',
        "anchors": [('2006', 'G80: the unified shader that made compute possible enters public record'), ('2007', 'Architecture or software sequel in trade press'), ('2024', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
        "photo": 'geforce-8800-gtx-board.jpg',
    },
    {
        "slug": '09-tesla-compute-without-a-monitor',
        "file": '09-tesla-compute-without-a-monitor.md',
        "title": 'Tesla: compute without a monitor',
        "chart": 'compute_sku',
        "anchors": [('2007', 'Tesla: compute without a monitor enters public record'), ('2008', 'Architecture or software sequel in trade press'), ('2026', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
        "photo": 'tesla-gpu-cluster.jpg',
    },
    {
        "slug": '10-fermi-caches-and-ecc',
        "file": '10-fermi-caches-and-ecc.md',
        "title": 'Fermi: caches, error correction, and a grown-up GPU',
        "chart": 'cache_hierarchy',
        "anchors": [('2010', 'Fermi: caches, error correction, and a grown-up GPU enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '11-supercomputers-notice-the-gpu',
        "file": '11-supercomputers-notice-the-gpu.md',
        "title": 'Supercomputers notice the graphics card',
        "chart": 'cluster_scale',
        "anchors": [('2006', 'Supercomputers notice the graphics card enters public record'), ('2010', 'Architecture or software sequel in trade press'), ('2012', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '12-two-gtx-580s-alexnet',
        "file": '12-two-gtx-580s-alexnet.md',
        "title": 'Two GTX 580s in a bedroom',
        "chart": 'dual_gpu',
        "anchors": [('2012', 'AlexNet paper: two GTX 580s, ~6 days'), ('2012', 'ILSVRC top-5 error step change'), ('2014', 'cuDNN hides conv details'), ('now', 'Bedroom scale vs datacenter scale')],
        "photo": 'gtx-580-die.jpg',
    },
    {
        "slug": '13-cudnn-the-library-that-hid-the-hardware',
        "file": '13-cudnn-the-library-that-hid-the-hardware.md',
        "title": 'cuDNN: the library that hid the hardware',
        "chart": 'software_stack',
        "anchors": [('2012', 'cuDNN: the library that hid the hardware enters public record'), ('2014', 'Architecture or software sequel in trade press'), ('2016', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '14-pascal-p100-hbm2-nvlink',
        "file": '14-pascal-p100-hbm2-nvlink.md',
        "title": 'Pascal P100: stacked memory and a new wire',
        "chart": 'memory_interconnect',
        "anchors": [('2007', 'Pascal P100: stacked memory and a new wire enters public record'), ('2010', 'Architecture or software sequel in trade press'), ('2015', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '15-volta-tensor-core',
        "file": '15-volta-tensor-core.md',
        "title": "Volta's Tensor Core: a multiply unit becomes a product",
        "chart": 'tensor_unit',
        "anchors": [('2017', "Volta's Tensor Core: a multiply unit becomes a produ enters public record"), ('2018', 'Architecture or software sequel in trade press'), ('2019', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '16-turing-rays-and-consumer-tensors',
        "file": '16-turing-rays-and-consumer-tensors.md',
        "title": 'Turing: real-time rays and the consumer tensor',
        "chart": 'tensor_unit',
        "anchors": [('2017', 'Turing: real-time rays and the consumer tensor enters public record'), ('2018', 'Architecture or software sequel in trade press'), ('2080', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '17-ampere-a100-mig',
        "file": '17-ampere-a100-mig.md',
        "title": 'Ampere A100 and the sliced GPU',
        "chart": 'partition_sku',
        "anchors": [('2018', 'Ampere A100 and the sliced GPU enters public record'), ('2020', 'Architecture or software sequel in trade press'), ('2022', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '18-hopper-transformer-factory',
        "file": '18-hopper-transformer-factory.md',
        "title": 'Hopper: the transformer as a product requirement',
        "chart": 'tensor_unit',
        "anchors": [('2017', 'Hopper: the transformer as a product requirement enters public record'), ('2022', 'Architecture or software sequel in trade press'), ('2023', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '19-blackwell-the-rack-is-the-chip',
        "file": '19-blackwell-the-rack-is-the-chip.md',
        "title": 'Blackwell: when the rack is the chip',
        "chart": 'rack_scale',
        "anchors": [('1999', 'Blackwell: when the rack is the chip enters public record'), ('2016', 'Architecture or software sequel in trade press'), ('2022', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '20-grids-blocks-threads',
        "file": '20-grids-blocks-threads.md',
        "title": "Grids, blocks, threads: CUDA's street map",
        "chart": 'cuda_hierarchy',
        "anchors": [('2007', "Grids, blocks, threads: CUDA's street map enters public record"), ('2015', 'Architecture or software sequel in trade press'), ('2025', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '21-the-warp-thirty-two-threads',
        "file": '21-the-warp-thirty-two-threads.md',
        "title": 'The warp: thirty-two threads that live or die together',
        "chart": 'cuda_hierarchy',
        "anchors": [('2011', 'The warp: thirty-two threads that live or die togeth enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '22-occupancy-is-not-performance',
        "file": '22-occupancy-is-not-performance.md',
        "title": 'Occupancy is not performance',
        "chart": 'cuda_hierarchy',
        "anchors": [('now', 'Cross-check dates in essay Sources'), ('era', 'Verify milestone years in prose'), ('era', 'Verify milestone years in prose')],
    },
    {
        "slug": '23-shared-memory-scratchpad',
        "file": '23-shared-memory-scratchpad.md',
        "title": 'Shared memory: the scratchpad that taught a generation',
        "chart": 'memory_hierarchy',
        "anchors": [('2008', 'Shared memory: the scratchpad that taught a generati enters public record'), ('2014', 'Architecture or software sequel in trade press'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '24-unified-memory-hid-the-copies',
        "file": '24-unified-memory-hid-the-copies.md',
        "title": 'Unified memory: the API that hid the copies',
        "chart": 'memory_hierarchy',
        "anchors": [('2014', 'Unified memory: the API that hid the copies enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '25-cuda-graphs-launch-tax',
        "file": '25-cuda-graphs-launch-tax.md',
        "title": 'CUDA Graphs and the tax of launching a kernel',
        "chart": 'launch_overhead',
        "anchors": [('2017', 'CUDA Graphs and the tax of launching a kernel enters public record'), ('2018', 'Architecture or software sequel in trade press'), ('2020', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '26-mixed-precision-bargain',
        "file": '26-mixed-precision-bargain.md',
        "title": 'Mixed precision: the accuracy bargain',
        "chart": 'precision_ladder',
        "anchors": [('2018', 'Mixed precision: the accuracy bargain enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '27-nccl-all-reduce',
        "file": '27-nccl-all-reduce.md',
        "title": 'NCCL: all-reduce as industrial plumbing',
        "chart": 'collective_ring',
        "anchors": [('2016', 'NCCL: all-reduce as industrial plumbing enters public record'), ('2017', 'Architecture or software sequel in trade press'), ('2024', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '28-nvlink-nvswitch-midplane',
        "file": '28-nvlink-nvswitch-midplane.md',
        "title": 'NVLink and NVSwitch: the midplane',
        "chart": 'memory_interconnect',
        "anchors": [('2016', 'NVLink and NVSwitch: the midplane enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '29-dgx-1-eight-gpus',
        "file": '29-dgx-1-eight-gpus.md',
        "title": 'DGX-1: eight GPUs and a category',
        "chart": 'cluster_scale',
        "anchors": [('Apr 2016', 'DGX-1 announced with P100'), ('2017', 'Eight-GPU box as category'), ('2020', 'A100 generation refresh'), ('now', 'Appliance SKU, not a hobby rack')],
        "photo": 'nvidia-dgx-front.jpg',
    },
    {
        "slug": '30-the-cuda-moat',
        "file": '30-the-cuda-moat.md',
        "title": 'The CUDA moat: lock-in, libraries, and habit',
        "chart": 'ecosystem_moat',
        "anchors": [('2008', 'The CUDA moat: lock-in, libraries, and habit enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '31-opencl-the-standard-that-lost',
        "file": '31-opencl-the-standard-that-lost.md',
        "title": 'OpenCL: the standard that arrived on time and still lost',
        "chart": 'software_stack',
        "anchors": [('2008', 'OpenCL: the standard that arrived on time and still  enters public record'), ('2009', 'Architecture or software sequel in trade press'), ('2016', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '32-amd-firestream-rocm-hip',
        "file": '32-amd-firestream-rocm-hip.md',
        "title": "AMD's long compute detour",
        "chart": 'software_stack',
        "anchors": [('2007', "AMD's long compute detour enters public record"), ('2008', 'Architecture or software sequel in trade press'), ('2016', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '33-intel-third-chair',
        "file": '33-intel-third-chair.md',
        "title": "Intel's third chair",
        "chart": 'vendor_chair',
        "anchors": [('2019', "Intel's third chair enters public record"), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '34-tpu-v1-board-in-a-datacenter',
        "file": '34-tpu-v1-board-in-a-datacenter.md',
        "title": 'A board in a Google datacenter',
        "chart": 'systolic_board',
        "anchors": [('2016', 'TPU v1 paper at ISCA'), ('2017', 'Pods and cloud inference story'), ('2018', 'TPU v3 public discourse'), ('now', 'ASIC line beside general GPUs')],
        "photo": 'tpu-v4.png',
    },
    {
        "slug": '35-systolic-arrays-kung-to-jouppi',
        "file": '35-systolic-arrays-kung-to-jouppi.md',
        "title": 'Systolic arrays: an old idea Google shipped',
        "chart": 'systolic_board',
        "anchors": [('1979', 'Systolic arrays: an old idea Google shipped enters public record'), ('2015', 'Architecture or software sequel in trade press'), ('2016', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '36-tpu-pods-the-network-is-the-machine',
        "file": '36-tpu-pods-the-network-is-the-machine.md',
        "title": 'TPU pods: when the network is the machine',
        "chart": 'cluster_scale',
        "anchors": [('2017', 'TPU pods: when the network is the machine enters public record'), ('2024', 'Architecture or software sequel in trade press'), ('2026', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '37-xla-jax-compiling-for-a-chip',
        "file": '37-xla-jax-compiling-for-a-chip.md',
        "title": 'XLA and JAX: compiling for a chip you cannot buy',
        "chart": 'compiler_stack',
        "anchors": [('2018', 'XLA and JAX: compiling for a chip you cannot buy enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '38-why-tpus-and-gpus-coexist',
        "file": '38-why-tpus-and-gpus-coexist.md',
        "title": 'Why TPUs and GPUs kept not replacing each other',
        "chart": 'vendor_chair',
        "anchors": [('2016', 'Why TPUs and GPUs kept not replacing each other enters public record'), ('2017', 'Architecture or software sequel in trade press'), ('2023', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '39-memory-bandwidth-ate-the-decade',
        "file": '39-memory-bandwidth-ate-the-decade.md',
        "title": 'Memory bandwidth ate the decade',
        "chart": 'memory_hierarchy',
        "anchors": [('2008', 'Memory bandwidth ate the decade enters public record'), ('2009', 'Architecture or software sequel in trade press'), ('2010', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '40-hbm-stacking-dram',
        "file": '40-hbm-stacking-dram.md',
        "title": 'HBM: stacking DRAM until the package screamed',
        "chart": 'memory_interconnect',
        "anchors": [('1998', 'HBM: stacking DRAM until the package screamed enters public record'), ('2015', 'Architecture or software sequel in trade press'), ('2016', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '41-power-water-building-as-limit',
        "file": '41-power-water-building-as-limit.md',
        "title": 'Power, water, and the building as the limit',
        "chart": 'datacenter_limit',
        "anchors": [('2016', 'Power, water, and the building as the limit enters public record'), ('2024', 'Architecture or software sequel in trade press'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '42-training-vs-inference-silicon',
        "file": '42-training-vs-inference-silicon.md',
        "title": 'Training silicon and inference silicon are different animals',
        "chart": 'train_infer_split',
        "anchors": [('2017', 'Training silicon and inference silicon are different enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '43-the-sku-wall',
        "file": '43-the-sku-wall.md',
        "title": 'The SKU wall: GeForce, Quadro, Tesla, then Data Center',
        "chart": 'sku_ladder',
        "anchors": [('2007', 'The SKU wall: GeForce, Quadro, Tesla, then Data Cent enters public record'), ('era', 'Verify milestone years in prose'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '44-bitcoin-gamers-commodity',
        "file": '44-bitcoin-gamers-commodity.md',
        "title": 'Bitcoin, gamers, and the GPU as a commodity',
        "chart": 'market_demand',
        "anchors": [('2010', 'Bitcoin, gamers, and the GPU as a commodity enters public record'), ('2011', 'Architecture or software sequel in trade press'), ('2012', 'Datacenter or consumer SKU crossover'), ('now', 'Cross-check dates in essay Sources')],
    },
    {
        "slug": '45-what-a-flop-stopped-meaning',
        "file": '45-what-a-flop-stopped-meaning.md',
        "title": 'What a FLOP stopped meaning',
        "chart": 'flop_meter',
        "anchors": [('1999', 'Graphics peak FLOPs as marketing'), ('2012', 'Convnets care about memory too'), ('2020', 'Sparse / tensor FLOPs multiply'), ('now', 'Read the benchmark contract')],
    },
]
