#!/usr/bin/env python3
"""
FigRoots blog graphics pipeline.

Generates SVG assets under content/figroots-blog/assets/<slug>/,
embeds figures in draft markdown, updates `figures:` front matter,
and writes GRAPHICS_INDEX.md.

Usage:
  python content/figroots-blog/scripts/graphics_pipeline.py --all
  python content/figroots-blog/scripts/graphics_pipeline.py --slug fig-growing-degree-days
  python content/figroots-blog/scripts/graphics_pipeline.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
DRAFTS = ROOT / "drafts"
ASSETS = ROOT / "assets"
INDEX_PATH = ROOT / "GRAPHICS_INDEX.md"
CHECKLIST_PATH = ROOT / "GRAPHICS_CHECKLIST.md"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from figroots_graphics.generators import GENERATORS  # noqa: E402
from figroots_graphics.specs import ARTICLE_FIGURES, FigureSpec  # noqa: E402

MARKER_RE = re.compile(r"<!-- figroots-graphic: ([\w-]+) -->")
FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def parse_front_matter(text: str) -> tuple[dict, str, str]:
    m = FRONT_MATTER_RE.match(text)
    if not m:
        raise ValueError("missing YAML front matter")
    meta = yaml.safe_load(m.group(1)) or {}
    body = text[m.end() :]
    return meta, m.group(0), body


def slug_from_draft(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    meta, _, _ = parse_front_matter(text)
    slug = meta.get("slug")
    if not slug:
        raise ValueError(f"{path}: no slug in front matter")
    return slug


def relative_asset_path(slug: str, file_id: str) -> str:
    return f"../assets/{slug}/{file_id}.svg"


def embed_block(spec: FigureSpec, slug: str) -> str:
    rel = relative_asset_path(slug, spec.file_id)
    return (
        f"\n<!-- figroots-graphic: {spec.file_id} -->\n"
        f"![{spec.alt}]({rel})\n"
        f"*{spec.caption}*\n"
    )


def insert_after_heading(body: str, heading: str, block: str) -> str:
    marker = f"<!-- figroots-graphic: "
    if f"<!-- figroots-graphic: " in block:
        fid = re.search(r"<!-- figroots-graphic: ([\w-]+) -->", block).group(1)
        if f"<!-- figroots-graphic: {fid} -->" in body:
            return body
    idx = body.find(heading)
    if idx == -1:
        return body.rstrip() + "\n" + block
    line_end = body.find("\n", idx)
    if line_end == -1:
        return body + block
    return body[: line_end + 1] + block + body[line_end + 1 :]


def update_figures_front_matter(meta: dict, specs: list[FigureSpec], slug: str) -> None:
    paths = [relative_asset_path(slug, s.file_id) for s in specs]
    existing = meta.get("figures") or []
    merged: list[str] = []
    for p in existing + paths:
        if p not in merged:
            merged.append(p)
    meta["figures"] = merged


def generate_assets(slug: str, specs: list[FigureSpec], force: bool) -> list[str]:
    out_dir = ASSETS / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for spec in specs:
        dest = out_dir / f"{spec.file_id}.svg"
        if dest.exists() and not force:
            written.append(str(dest.relative_to(ROOT)))
            continue
        gen = GENERATORS.get(spec.generator)
        if not gen:
            raise KeyError(f"unknown generator {spec.generator}")
        try:
            gen(dest, spec)
        except TypeError:
            gen(dest)
        written.append(str(dest.relative_to(ROOT)))
    return written


def process_draft(path: Path, force: bool, dry_run: bool) -> dict:
    slug = slug_from_draft(path)
    specs = ARTICLE_FIGURES.get(slug)
    if not specs:
        return {"slug": slug, "file": path.name, "status": "no_specs", "figures": []}

    generate_assets(slug, specs, force=force)
    text = path.read_text(encoding="utf-8")
    meta, fm_raw, body = parse_front_matter(text)
    for spec in specs:
        body = insert_after_heading(body, spec.embed_after_heading, embed_block(spec, slug))
    update_figures_front_matter(meta, specs, slug)
    new_fm = "---\n" + yaml.safe_dump(meta, sort_keys=False, allow_unicode=True).strip() + "\n---\n"
    new_text = new_fm + body.lstrip("\n")
    if not dry_run:
        path.write_text(new_text, encoding="utf-8")
    return {
        "slug": slug,
        "file": path.name,
        "status": "ok",
        "figures": [s.file_id for s in specs],
    }


def write_graphics_index(results: list[dict]) -> None:
    lines = [
        "# FigRoots graphics index",
        "",
        "Auto-generated by `scripts/graphics_pipeline.py`. Draft/staged assets only.",
        "",
        "| Slug | Draft file | Figures | Asset folder |",
        "|---|---|---|---|",
    ]
    for r in sorted(results, key=lambda x: x.get("file", "")):
        if r.get("status") != "ok":
            continue
        slug = r["slug"]
        figs = ", ".join(f"`{f}.svg`" for f in r["figures"])
        lines.append(f"| `{slug}` | `{r['file']}` | {figs} | `assets/{slug}/` |")
    lines.append("")
    INDEX_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_checklist(ok_slugs: set[str], all_draft_slugs: set[str] | None = None) -> None:
    """Checklist against the actual 40-draft pack, not old placeholder slugs."""
    all_draft_slugs = all_draft_slugs or ok_slugs
    missing = sorted(all_draft_slugs - ok_slugs)
    lines = [
        "# FigRoots graphics checklist (40-draft pack)",
        "",
        f"**Current drafts with graphics:** {len(ok_slugs)} / {len(all_draft_slugs)}",
        "",
        "Re-run `python content/figroots-blog/scripts/graphics_pipeline.py --all` when headings or specs change.",
        "",
        "Existing 1–12 asset paths stay under `assets/<slug>/`. New slugs add figures beside them.",
        "",
        "## Shipped",
        "",
    ]
    for slug in sorted(ok_slugs):
        lines.append(f"- [x] `{slug}` — specs in `scripts/figroots_graphics/specs.py`")
    lines.extend(["", "## Drafts still missing specs", ""])
    if missing:
        for slug in missing:
            lines.append(f"- [ ] `{slug}`")
    else:
        lines.append("- none")
    lines.extend(
        [
            "",
            "## When a new draft appears",
            "",
            "1. Add `FigureSpec` entries to `scripts/figroots_graphics/specs.py` (or a generator).",
            "2. Run `graphics_pipeline.py --slug <slug>`.",
            "3. Confirm `figures:` in front matter and embed markers `<!-- figroots-graphic: ... -->`.",
            "4. Keep existing `../assets/<slug>/<file_id>.svg` paths if the slug already shipped.",
            "",
        ]
    )
    CHECKLIST_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="FigRoots blog graphics pipeline")
    parser.add_argument("--all", action="store_true", help="Process every draft")
    parser.add_argument("--slug", help="Process one slug (from front matter)")
    parser.add_argument("--force", action="store_true", help="Regenerate SVG even if present")
    parser.add_argument("--dry-run", action="store_true", help="Do not write markdown")
    parser.add_argument("--check", action="store_true", help="Exit 1 if any draft lacks specs")
    args = parser.parse_args()

    draft_files = sorted(DRAFTS.glob("*.md"))
    if not draft_files:
        print("No drafts found", file=sys.stderr)
        return 1

    targets: list[Path] = []
    if args.slug:
        for p in draft_files:
            if slug_from_draft(p) == args.slug:
                targets.append(p)
        if not targets:
            print(f"No draft with slug {args.slug}", file=sys.stderr)
            return 1
    elif args.all or args.check:
        targets = draft_files
    else:
        parser.print_help()
        return 1

    results: list[dict] = []
    missing: list[str] = []
    for p in targets:
        slug = slug_from_draft(p)
        if slug not in ARTICLE_FIGURES:
            missing.append(f"{p.name} ({slug})")
            results.append({"slug": slug, "file": p.name, "status": "no_specs", "figures": []})
            continue
        if args.check:
            results.append({"slug": slug, "file": p.name, "status": "ok", "figures": []})
            continue
        results.append(process_draft(p, force=args.force, dry_run=args.dry_run))

    if not args.check:
        write_graphics_index(results)
        write_checklist(
            {r["slug"] for r in results if r.get("status") == "ok"},
            {slug_from_draft(p) for p in draft_files},
        )

    if missing:
        print("Missing specs for:", ", ".join(missing), file=sys.stderr)
        return 1 if args.check else 0

    print(f"Processed {len(targets)} draft(s). Assets under {ASSETS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
