"""Find optional doors from installs/DOORS.toml. Does not download them.

A path in LOCAL.toml is this machine. A missing file is missing, not a pass.
The catalog names how a new machine obtains the door. It does not vendor the binary.
"""

from __future__ import annotations

import shutil
import tomllib
from pathlib import Path

from g47.refuse import Refuse

_REPO = Path(__file__).resolve().parents[3]
CATALOG = _REPO / "installs" / "DOORS.toml"
LOCAL = _REPO / "installs" / "LOCAL.toml"
_ROOTS = (Path(r"V:\\"), _REPO / "installs")


def catalog(path: Path | None = None) -> list[dict[str, str]]:
    """Read the committed door catalog. An absent file is a refusal, not an empty catalog."""
    src = path or CATALOG
    if not src.is_file():
        raise Refuse("CATALOG_ABSENT", str(src))
    data = tomllib.loads(src.read_text(encoding="utf-8"))
    rows = data.get("door") or []
    return [dict(row) for row in rows if isinstance(row, dict)]


def _local_tree(name: str, roots: tuple[Path, ...]) -> str:
    if not name:
        return ""
    for root in roots:
        candidate = root / name
        try:
            if candidate.is_dir() and any(candidate.iterdir()):
                return str(candidate)
        except OSError:
            continue
    return ""


def probe(
    rows: list[dict[str, str]] | None = None,
    *,
    which=shutil.which,
    roots: tuple[Path, ...] = _ROOTS,
) -> list[dict[str, str]]:
    """Resolve each catalog row. `which` and `roots` are injectable for tests."""
    found: list[dict[str, str]] = []
    for row in rows if rows is not None else catalog():
        binary = str(row.get("binary") or "")
        binary_found = ""
        if binary:
            hit = which(binary)
            binary_found = "" if hit is None else str(hit)
        local = _local_tree(str(row.get("local_name") or ""), roots)
        if binary_found or local:
            state = "found"
        else:
            state = "missing"
        found.append({
            "id": str(row.get("id") or ""),
            "binary": binary,
            "binary_found": binary_found,
            "local": local,
            "obtain": str(row.get("obtain") or ""),
            "wire_api": str(row.get("wire_api") or ""),
            "state": state,
        })
    return found


def write_local(path: Path | None = None) -> Path:
    """Write this machine's resolved paths. The catalog stays the source of names."""
    dest = path or LOCAL
    rows = probe()
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by py -3.14 -m g47 locate. This machine only.",
        "",
    ]
    for row in rows:
        lines.append("[[door]]")
        for key in ("id", "binary", "binary_found", "local", "obtain", "wire_api", "state"):
            value = row[key].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key} = "{value}"')
        lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return dest
