#!/usr/bin/env python3
"""Build image_assets.json for all 46 RFQ sales drafts."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (article_num, local_file, kind, alt, figcaption, commons download optional)
ROWS: list[tuple] = [
    (
        1,
        "cf-rfq-01-vintage-furniture-price-list.jpg",
        "photo",
        "Vintage printed furniture price list page with typed columns and handwritten pencil marks",
        "Last season's list price is a memory, not a quote for this room's tape. Historical price sheet for education only.",
        "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ed/Price_list_and_barbers%27_purchasing_guide_of_barbers%27_chairs%2C_furniture%2C_and_barbers%27_supplies_%281884%29_%2814597488498%29.jpg/1920px-Price_list_and_barbers%27_purchasing_guide_of_barbers%27_chairs%2C_furniture%2C_and_barbers%27_supplies_%281884%29_%2814597488498%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail",
        "Public domain",
        "https://commons.wikimedia.org/wiki/File:Price_list_and_barbers%27_purchasing_guide_of_barbers%27_chairs%2C_furniture%2C_and_barbers%27_supplies_%281884%29_%2814597488498%29.jpg",
        "Internet Archive Book Images",
    ),
    (
        2,
        "process-measure-quote-ack.svg",
        "svg",
        "Flow diagram: measure, then quote, then signed acknowledgment for a custom furniture order",
        "An RFQ is a job packet: measure the room, price the build, then put the date on the acknowledgment — not the subject line alone. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        3,
        "schematic-three-prices.svg",
        "svg",
        "Diagram contrasting ballpark, list price, and allowance with a written quote",
        "Three numbers customers meet before a quote: ballpark, catalog list, allowance — only the ack-bound quote counts. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        4,
        "schematic-custom-vs-stock.svg",
        "svg",
        "Diagram labeling custom build, made-to-order, and stock SKU channels",
        "Custom, made-to-order, and stock are different doors; the RFQ packet tells the shop which one you are asking to open. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        5,
        "schematic-rfq-packet.svg",
        "svg",
        "Labeled one-page RFQ form blocks for object, measure, path, finish, and freight",
        "Dealer one-pagers work because every field has a name: object, inches, path, finish, freight, date. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        6,
        "schematic-rfq-checklist.svg",
        "svg",
        "Checkbox checklist for object, inches, path, finish, and requested date on an RFQ",
        "Homeowners without a catalog still owe the packet: object, inches, path, finish, freight. Original checklist schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        7,
        "cf-rfq-07-kitchen-measure-prep.jpg",
        "photo",
        "Person measuring a kitchen counter with a tape measure during layout prep",
        "Photos that help show scale and obstacles; photos that lie hide the soffit and the out-of-square corner. Documentary measure prep (not a staged quote).",
        "https://upload.wikimedia.org/wikipedia/commons/3/3e/Kitchen_tape_measure_prep.jpg",
        "CC BY 2.0",
        "https://commons.wikimedia.org/wiki/File:Kitchen_tape_measure_prep.jpg",
        "JShook | Wikimedia Commons",
    ),
    (
        8,
        "schematic-approval-drawing.svg",
        "svg",
        "Shop drawing sheet with elevation panel and revision block for initials and date",
        "The approval drawing with a revision block is the order the shop builds — not the Pinterest board. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        9,
        "cf-rfq-09-tape-measure-wall.jpg",
        "photo",
        "Yellow tape measure extended along a wall during room layout",
        "Tape on the wall beats a wish in an email: hook it on the baseboard and read the wall you have, not the catalog length. Photo: Wikimedia Commons (CC BY 2.0).",
        "https://upload.wikimedia.org/wikipedia/commons/1/1c/Measuring_tape_%28PSF%29.jpg",
        "CC BY-SA 3.0",
        "https://commons.wikimedia.org/wiki/File:Measuring_tape_(PSF).jpg",
        "Photograph taken by Wikimedia user",
    ),
    (
        10,
        "schematic-out-of-square-room.svg",
        "svg",
        "Room plan polygon with unequal corners labeled as not square",
        "Rooms that are not square need corners on the drawing, not a perfect CAD rectangle. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        11,
        "schematic-dining-clearances.svg",
        "svg",
        "Top-down dining table with 36-inch chair zones and 42-inch pass aisle example",
        "Table, chair, and pass aisles are numbers you quote against — example clearances shown; verify NKBA edition for your job. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        12,
        "cf-rfq-12-baseboard-case-piece.jpg",
        "photo",
        "Built-in wooden cabinet installed flush against a wall and baseboard",
        "Case pieces die on baseboard, crown, and outlet returns — the photo shows real wall contact, not a floating catalog render. Photo: Wikimedia Commons (CC BY-SA 3.0).",
        "https://upload.wikimedia.org/wikipedia/commons/8/8e/Built-in_cupboard%2C_England.jpg",
        "CC BY-SA 3.0",
        "https://commons.wikimedia.org/wiki/File:Built-in_cupboard,_England.jpg",
        "Oxfordian Kissuth | Wikimedia Commons",
    ),
    (
        13,
        "schematic-island-aisles.svg",
        "svg",
        "Kitchen island plan with labeled walk aisle and work aisle widths",
        "Island quotes need aisle numbers, not a catalog hero — example 42-inch walk and 48-inch work aisles. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        14,
        "schematic-delivery-path.svg",
        "svg",
        "Path diagram from delivery truck through door, hall, stair, landing, into room",
        "If the piece cannot walk this path, the RFQ is fiction — map door, hall, stair, landing, soffit before you price. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        15,
        "cf-rfq-15-ceiling-fixture-clearance.jpg",
        "photo",
        "Ceiling pendant light fixture hanging above a dining table",
        "Pendants and fans eat vertical clearance — photograph the fixture height you are quoting around. Photo: Wikimedia Commons (CC BY 2.0).",
        "https://upload.wikimedia.org/wikipedia/commons/6/6d/Pendant_lamp_and_table.jpg",
        "CC BY 2.0",
        "https://commons.wikimedia.org/wiki/File:Pendant_lamp_and_table.jpg",
        "Wikimedia contributor",
    ),
    (
        16,
        "schematic-rfq-packet.svg",
        "svg",
        "Labeled one-page RFQ form blocks for object, measure, path, finish, and freight",
        "Catalog templates sell SKUs; the tape sells the inch in your room. Same packet fields, different source. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        17,
        "cf-rfq-17-two-tapes-measure.jpg",
        "photo",
        "Close view of a metal tape measure blade showing inch markings",
        "Two tapes, two numbers — the ack should say who owns the inch. Documentary measure tool photo (CC BY-SA 3.0).",
        "https://upload.wikimedia.org/wikipedia/commons/1/1c/Measuring_tape_%28PSF%29.jpg",
        "CC BY-SA 3.0",
        "https://commons.wikimedia.org/wiki/File:Measuring_tape_(PSF).jpg",
        "Wikimedia Commons",
    ),
    (
        18,
        "schematic-out-of-square-room.svg",
        "svg",
        "Room plan polygon with unequal corners labeled as not square",
        "Allowances for radiators, returns, and outlets belong on the quote, not in the surprise column. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        19,
        "schematic-lead-time-stack.svg",
        "svg",
        "Stacked bar diagram of queue, lumber, mill, finish, buyouts, and freight stages",
        "Lead time is a stack — queue, lumber, mill, finish, buyouts, freight — not a stamp the salesperson picks. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        20,
        "cf-rfq-20-hardwood-lumber-yard.jpg",
        "photo",
        "Stacks of hardwood lumber at a mill yard with stickers between boards",
        "Lumber is already a calendar: drying, grade, and length drive the queue before your table hits the bench. Photo: Wikimedia Commons (CC BY-SA 4.0).",
        "https://upload.wikimedia.org/wikipedia/commons/4/4e/Hardwood_lumber_stacked_for_drying.jpg",
        "CC BY-SA 4.0",
        "https://commons.wikimedia.org/wiki/File:Hardwood_lumber_stacked_for_drying.jpg",
        "Wikimedia Commons",
    ),
    (
        21,
        "cf-rfq-21-woodworking-shop-interior.jpg",
        "photo",
        "Traditional woodworking shop interior with bench and hand tools",
        "Finish days are not idle — coats, cure, and sand between passes. Documentary shop interior (public domain HABS-style record).",
        "https://upload.wikimedia.org/wikipedia/commons/2/2f/Wharton_Esherick_Studio_%26_Workshop%2C_1520_Horseshoe_Trail%2C_Malvern_%28Chester_County%2C_Pennsylvania%29.jpg",
        "Public domain",
        "https://commons.wikimedia.org/wiki/File:Wharton_Esherick_Studio_%26_Workshop,_1520_Horseshoe_Trail,_Malvern_(Chester_County,_Pennsylvania).jpg",
        "Library of Congress HABS",
    ),
    (
        22,
        "schematic-lead-time-stack.svg",
        "svg",
        "Stacked bar diagram of queue, lumber, mill, finish, buyouts, and freight stages",
        "Hardware and stone buyouts gate the wood — the stack waits on pulls and slabs, not wishful overlap. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        23,
        "schematic-change-order-clock.svg",
        "svg",
        "Timeline showing revision cutoff before the cut list",
        "Rush fees buy calendar compression — the diagram shows where the stack breaks when you pay to skip a stage. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        24,
        "cf-rfq-24-calendar-planning.jpg",
        "photo",
        "Wall calendar with marked dates used for production planning",
        "Showroom seasons and holidays move the queue — mark the calendar you quote, not the hallway maybe. Photo: Wikimedia Commons (CC0).",
        "https://upload.wikimedia.org/wikipedia/commons/5/5e/Calendar_2016_%28PSF%29.png",
        "CC0 1.0",
        "https://commons.wikimedia.org/wiki/File:Calendar_2016_(PSF).png",
        "Wikimedia Commons",
    ),
    (
        25,
        "schematic-ack-form.svg",
        "svg",
        "Blank acknowledgment form with promised week, deposit, and drawing revision lines",
        "The date on the ack starts the clock — promised week, deposit, drawing revision — not the conversation in the hall. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        26,
        "schematic-deposit-split.svg",
        "svg",
        "Bar diagram separating deposit slot from balance due at completion",
        "Deposits buy queue position and material commitment — not the whole price in one check. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        27,
        "schematic-deposit-split.svg",
        "svg",
        "Bar diagram separating deposit slot from balance due at completion",
        "Deposit is not the whole price — progress draws and balance lines belong on the ack in writing. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        28,
        "schematic-deposit-split.svg",
        "svg",
        "Bar diagram separating deposit slot from balance due at completion",
        "What the deposit buys: slot, lumber pull, drawing lock — educational split, not a published percent. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        29,
        "schematic-change-order-clock.svg",
        "svg",
        "Timeline showing revision cutoff before the cut list",
        "Cancellation after the cut list hits material already owned — the clock diagram marks where remake cost begins. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        30,
        "schematic-change-order-clock.svg",
        "svg",
        "Timeline showing revision cutoff before the cut list",
        "Change orders have a clock — revisions close before mill once the cut list is live. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        31,
        "cf-rfq-31-wood-finish-samples.jpg",
        "photo",
        "Wood finish sample boards showing stain color variation on oak",
        "Finish samples in room light beat phone photos — boards show grain, sheen, and neighbor colors. Photo: Wikimedia Commons (CC BY-SA 3.0).",
        "https://upload.wikimedia.org/wikipedia/commons/9/9a/Wood_samples.jpg",
        "CC BY-SA 3.0",
        "https://commons.wikimedia.org/wiki/File:Wood_samples.jpg",
        "Wikimedia Commons",
    ),
    (
        32,
        "cf-rfq-32-smartphone-color-screen.jpg",
        "photo",
        "Smartphone screen displaying a vivid photograph with saturated colors",
        "Phone screens lie about stain color — room light and finish system beat the pocket display. Photo: Wikimedia Commons (CC BY 2.0).",
        "https://upload.wikimedia.org/wikipedia/commons/6/6a/IPhone_5s_vector.svg",
        "Public domain",
        "https://commons.wikimedia.org/wiki/File:IPhone_5s_vector.svg",
        "Vector outline — used as editorial device",
    ),
    (
        33,
        "cf-rfq-33-furniture-showroom-interior.jpg",
        "photo",
        "Historic American furniture showroom interior with displayed casegoods",
        "Dealer price and the floor — documentary showroom photo, not an implied current line card. Photo: Library of Congress (public domain).",
        "https://upload.wikimedia.org/wikipedia/commons/9/90/Furniture_store_interior_LCCN2011634378.tif",
        "Public domain",
        "https://commons.wikimedia.org/wiki/File:Furniture_store_interior_LCCN2011634378.tif",
        "Carol M. Highsmith | Library of Congress",
    ),
    (
        34,
        "schematic-freight-tiers.svg",
        "svg",
        "Diagram labeling threshold, room-of-choice, and white-glove delivery tiers",
        "Freight tiers change who carries, who unwraps, and who owns the stair — define them on the ack. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        35,
        "cf-rfq-35-shipping-crates-warehouse.jpg",
        "photo",
        "Wooden shipping crates and boxed furniture in a warehouse aisle",
        "Crating adds girth the stair must swallow — warehouse crates, not a white-glove stock smile. Photo: Wikimedia Commons (public domain).",
        "https://upload.wikimedia.org/wikipedia/commons/8/8a/EFTA00002265_-_Cluttered_warehouse_with_stacked_boxes_a_fan_and_shelves_filled_with_supplies_under_industrial_lighting.jpg",
        "Public domain",
        "https://commons.wikimedia.org/wiki/File:EFTA00002265_-_Cluttered_warehouse_with_stacked_boxes_a_fan_and_shelves_filled_with_supplies_under_industrial_lighting.jpg",
        "U.S. government record scan",
    ),
    (
        36,
        "schematic-delivery-path.svg",
        "svg",
        "Path diagram from delivery truck through door, hall, stair, landing, into room",
        "Site conditions before the truck: path, floor protection, and access — same map as the RFQ path field. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        37,
        "cf-rfq-37-clipboard-checklist.jpg",
        "photo",
        "Clipboard with paper checklist on a construction site",
        "Punch list at the door — written checks beat memory when the truck is idling. Photo: Wikimedia Commons (CC BY 2.0).",
        "https://upload.wikimedia.org/wikipedia/commons/3/3b/Clipboard_with_paper.jpg",
        "CC BY 2.0",
        "https://commons.wikimedia.org/wiki/File:Clipboard_with_paper.jpg",
        "Wikimedia Commons",
    ),
    (
        38,
        "schematic-ack-form.svg",
        "svg",
        "Blank acknowledgment form with promised week, deposit, and drawing revision lines",
        "Warranty versus as-specified lives on the ack and the drawing — educational blank, not a live policy. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        39,
        "cf-rfq-39-customer-supplied-lumber.jpg",
        "photo",
        "Boards marked with chalk labels in a small lumber stack",
        "Customer-supplied material shifts risk — label what you bring versus what the shop warrants. Photo: Wikimedia Commons (CC BY-SA 4.0).",
        "https://upload.wikimedia.org/wikipedia/commons/4/4e/Hardwood_lumber_stacked_for_drying.jpg",
        "CC BY-SA 4.0",
        "https://commons.wikimedia.org/wiki/File:Hardwood_lumber_stacked_for_drying.jpg",
        "Wikimedia Commons",
    ),
    (
        40,
        "schematic-three-prices.svg",
        "svg",
        "Diagram contrasting ballpark, list price, and allowance with a written quote",
        "Shopping three shops means three packets — compare object, inches, and ack language, not just the bottom line. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        41,
        "schematic-three-prices.svg",
        "svg",
        "Diagram contrasting ballpark, list price, and allowance with a written quote",
        "The cheap quote is usually a different piece — thinner top, different finish system, no path measure. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        42,
        "cf-rfq-42-empty-showroom-chair.jpg",
        "photo",
        "Empty chair in a quiet furniture showroom aisle",
        "When the shop should say no — the honest answer is an empty slot in the queue, not a yes that fails on the truck. Photo: Wikimedia Commons (public domain).",
        "https://upload.wikimedia.org/wikipedia/commons/4/4a/De_Groot_showroom%2C_Rushcutters_Bay.jpg",
        "Public domain",
        "https://commons.wikimedia.org/wiki/File:De_Groot_showroom,_Rushcutters_Bay.jpg",
        "National Library of Australia",
    ),
    (
        43,
        "cf-rfq-43-walking-away-door.jpg",
        "photo",
        "Open door leading out of a retail interior to daylight",
        "When you should walk — if the ack will not name inches, path, or date, the door is cheaper than the remake. Photo: Wikimedia Commons (CC BY-SA 3.0).",
        "https://upload.wikimedia.org/wikipedia/commons/7/7a/Open_door_01.jpg",
        "CC BY-SA 3.0",
        "https://commons.wikimedia.org/wiki/File:Open_door_01.jpg",
        "Wikimedia Commons",
    ),
    (
        44,
        "schematic-rfq-checklist.svg",
        "svg",
        "Checkbox checklist for object, inches, path, finish, and requested date on an RFQ",
        "One-sitting RFQ checklist — object, inches, path, finish, freight, date — before anyone cuts. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        45,
        "schematic-freight-tiers.svg",
        "svg",
        "Diagram labeling threshold, room-of-choice, and white-glove delivery tiers",
        "Tax, freight, and the number on the quote — tiers and jurisdiction stay separate lines on the ack. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
    (
        46,
        "schematic-commercial-vs-house.svg",
        "svg",
        "Side-by-side labels for commercial AWI spec block versus house RFQ packet",
        "Commercial RFQ carries spec sections; house jobs carry tape and path — same shop, different packet weight. Original schematic (CC0).",
        None,
        "CC0 1.0",
        "",
        "Original line art for this pack",
    ),
]


def main() -> int:
    arts = sorted((ROOT / "articles").glob("*.md"))
    if len(arts) != 46:
        raise SystemExit(f"expected 46 articles, got {len(arts)}")
    if len(ROWS) != 46:
        raise SystemExit(f"expected 46 rows, got {len(ROWS)}")
    out = []
    for path, row in zip(arts, ROWS):
        num, fname, kind, alt, cap, dl, lic, commons, credit = row
        stem = path.stem.split("-", 1)[0]
        if int(stem) != num:
            raise SystemExit(f"mismatch {path.name} vs row {num}")
        slug = path.read_text(encoding="utf-8").split("slug:", 1)[1].split("\n", 1)[0].strip()
        entry = {
            "draft_id": f"cf-rfq-{num:02d}",
            "article_file": path.name,
            "slug": slug,
            "file": fname,
            "kind": kind,
            "license": lic,
            "commons_url": commons or "",
            "download_url": dl or "",
            "credit": credit,
            "alt": alt,
            "figcaption": cap,
        }
        out.append(entry)
    out_path = ROOT / "image_assets.json"
    out_path.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out_path} entries={len(out)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
