#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""test_refusal_taxonomy.py -- F-40 leftover: regen is automatic, drift cannot skip.

docs/REFUSAL_TAXONOMY.md drifted THREE times today because a kind landed
in cosmos/*.py and the projection was only regenerated by hand
(``py -3.14 cosmos/cosmos_refusals.py --out docs/REFUSAL_TAXONOMY.md``).
tests/test_refusals.py already diffs -- it even prints a command -- but
(1) an absent doc is SKIPPED (counted as pass), (2) the generated doc
still tells you to use ``>`` which mangles em-dashes on a Windows
console, (3) nobody runs the hand regen, so the red sits until a human
pastes. --diff/--write existed and the supervisor still pasted --out:
a tool you have to remember is a tool that will be skipped.

This suite is collected by the selftest clock (``builds/*/test_*.py``).
It does NOT weaken test_refusals.py: that file is untouched and still
fails on drift. This one:

  * FAILS an absent projection (skip is the rot)
  * FAILS a drifted fixture, with the exact ``--out`` command
  * heals the live doc on drift so the NEXT clock tick is green
  * pins that a cp437 stdout redirect would itself be drift
  * stale_in / refresh_if_stale / --check (remeasure_probes shape)
  * default (no flags) heals stale and exits 0 -- the hand paste is gone
  * --check exits 1 on drift and does not write
  * a scratch copy with an extra refusal kind is caught and healed

Bite first: ``_bite_refusal_taxonomy_absent.json`` was written while
this module did not exist (ModuleNotFoundError). The drift / skip /
cp437 bites are recorded to ``_bite_refusal_taxonomy.json`` from a
fixture whose answer is known. Fail-against-old:
``_fail_taxonomy_remeasure_against_old.json`` on the pre-remeasure
incumbent. Scratch-kind proof: ``_bite_taxonomy_kind.json``.

    py -3.14 builds/probe/test_refusal_taxonomy.py

Hermetic except the live projection check, which reads (and on drift,
writes) docs/REFUSAL_TAXONOMY.md. Set COSMOS_TAXONOMY_HEAL=0 to compare
the live doc without writing. COSMOS_SKIP_TAXONOMY_REMEASURE=1 is the
bite hatch that must observe stale (refresh_if_stale becomes a no-op).
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))

import regen_refusal_taxonomy as regen  # noqa: E402

BITE_ABSENT = HERE / "_bite_refusal_taxonomy_absent.json"
BITE = HERE / "_bite_refusal_taxonomy.json"
BITE_KIND = HERE / "_bite_taxonomy_kind.json"
TICK = HERE / "_refusal_taxonomy_tick.json"
FAIL_OLD = HERE / "_fail_taxonomy_remeasure_against_old.json"
STAGED_OLD = HERE / "_delme" / "predispose_taxonomy_remeasure_20260831T184950Z"
SCRATCH_KIND = "SCRATCH_KIND_PROBE"
RESULTS: list[tuple[str, bool, str]] = []


def check(label, fn):
    try:
        RESULTS.append((label, bool(fn()), ""))
    except Exception as e:                                            # noqa: BLE001
        RESULTS.append((label, False, f"{type(e).__name__}: {e}"))


def old_test_refusals_absent_is_skip(doc_exists: bool) -> bool:
    """Reconstructed from tests/test_refusals.py:48-51.

    An absent projection is appended as True. That is the skip that lets
    a missing taxonomy stay missing. Proven here so the new check cannot
    quietly copy it.
    """
    if doc_exists:
        return False
    return True


def _cli(args, repo: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(HERE / "regen_refusal_taxonomy.py"),
         "--repo", str(repo), *args],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        cwd=str(REPO),
    )


def main() -> int:
    fresh, sv = regen.fresh_render()

    # ---- 1. the module was ABSENT ------------------------------------------
    check("absent-bite artifact exists", BITE_ABSENT.is_file)
    rec_abs = json.loads(BITE_ABSENT.read_text(encoding="utf-8")) if BITE_ABSENT.is_file() else {}
    check("absent-bite names ModuleNotFoundError",
          lambda: rec_abs.get("state") == "ABSENT"
          and rec_abs.get("kind") == "ModuleNotFoundError")
    check("the regenerator now imports from builds/probe",
          lambda: Path(regen.__file__).resolve().parent == HERE)

    # ---- 2. skip-on-absent is the rot; we FAIL instead ---------------------
    check("OLD test_refusals SKIP on absent would PASS",
          lambda: old_test_refusals_absent_is_skip(False) is True)
    td_abs = Path(tempfile.mkdtemp(prefix="cosmos_tax_abs_"))
    try:
        (td_abs / "docs").mkdir()
        absent = regen.tick(repo=td_abs, write=False)
        check("absent projection is DOC_ABSENT, not a skip",
              lambda: absent["kind"] == "DOC_ABSENT"
              and absent["match"] is False
              and absent["ok"] is False)
    finally:
        shutil.rmtree(td_abs, ignore_errors=True)

    # ---- 3. drifted fixture FAILS, matching fixture PASSES -----------------
    td = Path(tempfile.mkdtemp(prefix="cosmos_tax_"))
    try:
        docs = td / "docs"
        docs.mkdir()
        drifted_text = "DRIFTED — this is not a taxonomy\n"
        (docs / "REFUSAL_TAXONOMY.md").write_text(
            drifted_text, encoding="utf-8", newline="\n")
        drifted = regen.compare(drifted_text, fresh)
        check("a drifted fixture is kind=DRIFT match=false",
              lambda: drifted["kind"] == "DRIFT"
              and drifted["match"] is False
              and drifted["first_diff_line"] == 1)
        matched = regen.compare(fresh, fresh)
        check("identical strings are kind=MATCH",
              lambda: matched["kind"] == "MATCH" and matched["match"] is True)

        # ---- 4. --diff CLI exits 2 on drift and prints --out --------------
        p = _cli(["--diff"], td)
        out = (p.stdout or "") + (p.stderr or "")
        check("--diff on a drifted fixture exits 2", lambda: p.returncode == 2)
        check("--diff names the exact --out command",
              lambda: regen.REGEN_COMMAND in out)
        check("--diff tells you NOT to use '>'",
              lambda: "do NOT run:" in out and ">" in out)
        check("--diff command contains --out and not a redirect as the action",
              lambda: "--out" in regen.REGEN_COMMAND
              and ">" not in regen.REGEN_COMMAND)

        # ---- 4b. --check is the remesure detector: rc=1, no write ---------
        mtime_before_check = (docs / "REFUSAL_TAXONOMY.md").stat().st_mtime_ns
        p_chk = _cli(["--check"], td)
        try:
            chk_doc = json.loads(p_chk.stdout or "{}")
        except json.JSONDecodeError:
            chk_doc = {}
        check("--check on a drifted fixture exits 1",
              lambda: p_chk.returncode == 1)
        check("--check names docs/REFUSAL_TAXONOMY.md as stale",
              lambda: regen.ARTIFACT in (chk_doc.get("stale") or []))
        check("--check did not heal the drifted fixture",
              lambda: (docs / "REFUSAL_TAXONOMY.md").read_text(encoding="utf-8")
              == drifted_text
              and (docs / "REFUSAL_TAXONOMY.md").stat().st_mtime_ns
              == mtime_before_check)
        check("stale_in reports the drifted fixture",
              lambda: regen.stale_in(td) == [regen.ARTIFACT])

        # ---- 5. --write heals, still exits 2 this tick (noticed) ----------
        p2 = _cli(["--write", "--json-out", str(td / "tick.json")], td)
        out2 = (p2.stdout or "") + (p2.stderr or "")
        healed_disk = (docs / "REFUSAL_TAXONOMY.md").read_text(encoding="utf-8")
        check("--write on drift exits 2 (the red is the notice)",
              lambda: p2.returncode == 2)
        check("--write then the file MATCHES the fresh render",
              lambda: healed_disk == fresh)
        check("--write staged the incumbent under _delme",
              lambda: any((td / "_delme").glob("predispose_refusal_taxonomy_*/REFUSAL_TAXONOMY.md")))
        check("--write payload says healed=true kind=DRIFT",
              lambda: "healed this tick" in out2 or '"healed": true' in out2)

        p3 = _cli(["--diff"], td)
        check("--diff after heal exits 0", lambda: p3.returncode == 0)
    finally:
        shutil.rmtree(td, ignore_errors=True)

    # ---- 5b. default (no flags) heals and exits 0 -- the hand paste is gone
    td_def = Path(tempfile.mkdtemp(prefix="cosmos_tax_def_"))
    try:
        (td_def / "docs").mkdir()
        (td_def / "docs" / "REFUSAL_TAXONOMY.md").write_text(
            "DRIFTED — default-heal fixture\n", encoding="utf-8", newline="\n")
        p_def = _cli([], td_def)
        healed_def = (td_def / "docs" / "REFUSAL_TAXONOMY.md").read_text(
            encoding="utf-8")
        check("default (no flags) on drift exits 0 (remeasure shape, not --write's 2)",
              lambda: p_def.returncode == 0)
        check("default (no flags) then the file MATCHES the fresh render",
              lambda: healed_def == fresh)
        check("default (no flags) staged the incumbent under _delme",
              lambda: any((td_def / "_delme").glob(
                  "predispose_refusal_taxonomy_*/REFUSAL_TAXONOMY.md")))
        check("stale_in after default heal is empty",
              lambda: regen.stale_in(td_def) == [])
    finally:
        shutil.rmtree(td_def, ignore_errors=True)

    # ---- 5c. scratch copy + extra refusal kind: catch, then heal ----------
    live_doc = REPO / "docs" / "REFUSAL_TAXONOMY.md"
    live_mtime_before = live_doc.stat().st_mtime_ns if live_doc.is_file() else None
    td_kind = Path(tempfile.mkdtemp(prefix="cosmos_tax_kind_"))
    scratch_kind_found = False
    scratch_check_rc = None
    scratch_healed = False
    scratch_check_after_rc = None
    try:
        scratch_cosmos = td_kind / "cosmos"
        scratch_cosmos.mkdir()
        n_copied = 0
        for src in (REPO / "cosmos").glob("*.py"):
            shutil.copy2(src, scratch_cosmos / src.name)
            n_copied += 1
        (scratch_cosmos / "cosmos_scratch_kind_probe.py").write_text(
            "class ScratchKindProbeError(Exception):\n"
            '    """Typed refusal. kind in {SCRATCH_KIND_PROBE}."""\n'
            "\n"
            "    def __init__(self, kind: str, detail: str = '') -> None:\n"
            "        self.kind = kind\n"
            "        self.detail = detail\n"
            "        super().__init__(f'[{kind}] {detail}' if detail else f'[{kind}]')\n"
            "\n"
            "def _raise_for_survey() -> None:\n"
            "    raise ScratchKindProbeError('SCRATCH_KIND_PROBE', "
            "'taxonomy remesure proof')\n",
            encoding="utf-8", newline="\n")
        (td_kind / "docs").mkdir()
        if live_doc.is_file():
            shutil.copy2(live_doc, td_kind / "docs" / "REFUSAL_TAXONOMY.md")
        p_kind_chk = _cli(
            ["--check", "--code-dir", str(scratch_cosmos)], td_kind)
        scratch_check_rc = p_kind_chk.returncode
        try:
            kind_chk = json.loads(p_kind_chk.stdout or "{}")
        except json.JSONDecodeError:
            kind_chk = {}
        stale_kind = regen.stale_in(td_kind, code_dir=scratch_cosmos)
        scratch_sv_kinds = []
        try:
            _fresh_kind, _sv_kind = regen.fresh_render(code_dir=scratch_cosmos)
            scratch_sv_kinds = list(_sv_kind.get("kinds") or [])
            scratch_kind_found = SCRATCH_KIND in scratch_sv_kinds
        except Exception:                                              # noqa: BLE001
            scratch_kind_found = False
        check("scratch copied live cosmos/*.py",
              lambda: n_copied >= 40)
        check("scratch survey finds SCRATCH_KIND_PROBE (the planted kind)",
              lambda: scratch_kind_found is True)
        check("--check on scratch-with-extra-kind exits 1",
              lambda: scratch_check_rc == 1)
        check("stale_in names docs/REFUSAL_TAXONOMY.md after planting a kind",
              lambda: regen.ARTIFACT in stale_kind)
        check("--check report lists the taxonomy artifact as stale",
              lambda: regen.ARTIFACT in (kind_chk.get("stale") or []))
        rec_kind = regen.refresh_if_stale(
            repo=td_kind, code_dir=scratch_cosmos,
            label="AFTER-SCRATCH-KIND")
        healed_kind_text = (td_kind / "docs" / "REFUSAL_TAXONOMY.md").read_text(
            encoding="utf-8")
        scratch_healed = (
            rec_kind.get("stale_after") == []
            and SCRATCH_KIND in healed_kind_text
            and regen.ARTIFACT in (rec_kind.get("ran") or [])
        )
        check("refresh_if_stale heals the scratch projection",
              lambda: rec_kind.get("stale_after") == []
              and regen.ARTIFACT in (rec_kind.get("ran") or []))
        check("healed scratch projection contains SCRATCH_KIND_PROBE",
              lambda: SCRATCH_KIND in healed_kind_text)
        p_kind_after = _cli(
            ["--check", "--code-dir", str(scratch_cosmos)], td_kind)
        scratch_check_after_rc = p_kind_after.returncode
        check("--check after scratch heal exits 0",
              lambda: scratch_check_after_rc == 0)
        check("live docs/REFUSAL_TAXONOMY.md was not written by the scratch proof",
              lambda: live_mtime_before is not None
              and live_doc.stat().st_mtime_ns == live_mtime_before)
    finally:
        shutil.rmtree(td_kind, ignore_errors=True)

    bite_kind = {
        "what": "scratch copy + extra refusal kind is caught then healed",
        "scratch_kind": SCRATCH_KIND,
        "scratch_kind_found": scratch_kind_found,
        "check_rc_before": scratch_check_rc,
        "healed": scratch_healed,
        "check_rc_after": scratch_check_after_rc,
        "live_doc_untouched": (
            live_mtime_before is not None
            and live_doc.is_file()
            and live_doc.stat().st_mtime_ns == live_mtime_before
        ),
    }
    bite_kind["all_bite"] = (
        bite_kind["scratch_kind_found"] is True
        and bite_kind["check_rc_before"] == 1
        and bite_kind["healed"] is True
        and bite_kind["check_rc_after"] == 0
        and bite_kind["live_doc_untouched"] is True
    )
    BITE_KIND.write_text(json.dumps(bite_kind, indent=2, sort_keys=True) + "\n",
                         encoding="utf-8", newline="\n")
    check("scratch-kind bite all_bite is true",
          lambda: bite_kind["all_bite"] is True)

    # ---- 6. cp437 stdout redirect would itself be drift --------------------
    mangled = regen.cp437_mangle(fresh)
    check("the live render contains an em-dash the OEM page cannot hold",
          lambda: "\u2014" in fresh)
    check("a cp437 redirect of the render would NOT match UTF-8 --out",
          lambda: mangled != fresh)

    # ---- 7. selftest clock glob collects this file -------------------------
    collected = list((REPO / "builds").glob("*/test_*.py"))
    check("selftest clock glob builds/*/test_*.py includes this suite",
          lambda: any(p.resolve() == Path(__file__).resolve() for p in collected))
    check("tests/test_refusals.py is still on disk (not weakened, not deleted)",
          lambda: (REPO / "tests" / "test_refusals.py").is_file())

    # ---- 8. generator facts bind to a real survey --------------------------
    check("survey finds typed refusal classes on the live cosmos/",
          lambda: sv["typed_refusal_classes"] >= 40 and len(sv["kinds"]) >= 100)
    check("REGEN_COMMAND points at cosmos_refusals.py --out",
          lambda: regen.REGEN_COMMAND == (
              r"py -3.14 cosmos\cosmos_refusals.py --out docs\REFUSAL_TAXONOMY.md"))

    # BAD_ARGS is in TaxonomyRegenError.kind and in live_value["refusal_kinds"]
    # but was never exercised. --diff AND --write together must refuse, not
    # silently heal (a heal that nobody asked for is a write the operator
    # did not intend).
    def _diff_and_write_is_BAD_ARGS():
        try:
            regen.main(["--diff", "--write", "--repo", str(td_abs)])
        except regen.TaxonomyRegenError as e:
            return e.kind == "BAD_ARGS"
        return False
    check("--diff and --write together is BAD_ARGS, not a silent --write",
          _diff_and_write_is_BAD_ARGS)

    def _check_and_write_is_BAD_ARGS():
        try:
            regen.main(["--check", "--write", "--repo", str(td_abs)])
        except regen.TaxonomyRegenError as e:
            return e.kind == "BAD_ARGS"
        return False
    check("--check and --write together is BAD_ARGS, not a silent --write",
          _check_and_write_is_BAD_ARGS)

    def _check_and_diff_is_BAD_ARGS():
        try:
            regen.main(["--check", "--diff", "--repo", str(td_abs)])
        except regen.TaxonomyRegenError as e:
            return e.kind == "BAD_ARGS"
        return False
    check("--check and --diff together is BAD_ARGS, not two detectors at once",
          _check_and_diff_is_BAD_ARGS)

    regen_src = Path(regen.__file__).read_text(encoding="utf-8")
    test_src = Path(__file__).read_text(encoding="utf-8")
    check("stale_in exists (remeasure_probes shape)",
          lambda: "def stale_in" in regen_src)
    check("refresh_if_stale exists (remeasure_probes shape)",
          lambda: "def refresh_if_stale" in regen_src)
    check("--check flag exists and does not re-run / write",
          lambda: '"--check"' in regen_src and "do not re-run" in regen_src)
    check("COSMOS_SKIP_TAXONOMY_REMEASURE is the bite hatch",
          lambda: regen.SKIP_ENV == "COSMOS_SKIP_TAXONOMY_REMEASURE"
          and "COSMOS_SKIP_TAXONOMY_REMEASURE" in regen_src)
    check("this suite calls refresh_stale before the live MATCH gate",
          lambda: "refresh_stale" in test_src
          and "test_refusal_taxonomy.live_gate" in test_src)
    check("default CLI no longer forces --diff (old hand-paste path)",
          lambda: "if not a.diff and not a.write:" not in regen_src
          and "a.diff = True" not in regen_src)
    check("fail-against-old artifact exists", FAIL_OLD.is_file)
    fod = json.loads(FAIL_OLD.read_text(encoding="utf-8")) if FAIL_OLD.is_file() else {}
    check("fail-against-old all_new_pins_failed true "
          "(old regen had no stale_in / refresh_if_stale / --check)",
          lambda: fod.get("all_new_pins_failed") is True
          and fod.get("old_has_def_stale_in") is False
          and fod.get("old_has_def_refresh_if_stale") is False
          and fod.get("old_has_check_flag") is False)
    check("staged pre-remeasure incumbent still has no stale_in",
          lambda: STAGED_OLD.is_dir()
          and "def stale_in" not in (STAGED_OLD / "regen_refusal_taxonomy.py")
          .read_text(encoding="utf-8"))

    # NO_GENERATOR sat in TaxonomyRegenError.kind and live_value["refusal_kinds"]
    # with no test that actually deleted cosmos_refusals.py.
    old_cosmos = regen.COSMOS
    nogen = Path(tempfile.mkdtemp(prefix="cosmos_nogen_"))
    try:
        empty = nogen / "cosmos"
        empty.mkdir()
        regen.COSMOS = empty

        def _missing_generator_is_NO_GENERATOR():
            try:
                regen.load_generator()
            except regen.TaxonomyRegenError as e:
                return e.kind == "NO_GENERATOR"
            return False
        check("missing cosmos_refusals.py is NO_GENERATOR, not an ImportError",
              _missing_generator_is_NO_GENERATOR)
    finally:
        regen.COSMOS = old_cosmos
        shutil.rmtree(nogen, ignore_errors=True)

    # UNWRITABLE: mkdir was outside the try, so a file-as-parent was
    # FileExistsError. mkdir now lives in the same OSError wrapper.
    unw = Path(tempfile.mkdtemp(prefix="cosmos_unw_"))
    try:
        blocked = unw / "blocked"
        blocked.write_text("x", encoding="utf-8")

        def _parent_is_file_is_UNWRITABLE():
            try:
                regen.write_utf8(blocked / "out.md", "hello")
            except regen.TaxonomyRegenError as e:
                return e.kind == "UNWRITABLE"
            return False
        check("write whose parent is a file is UNWRITABLE, not FileExistsError",
              _parent_is_file_is_UNWRITABLE)
        check("UNWRITABLE did not clobber the blocking file",
              lambda: blocked.read_text(encoding="utf-8") == "x")

        # Write succeeds, read-back does not match: documented UNWRITABLE
        # that parent-is-file never hit. Bite: stripped after!=fresh
        # reported healed over WRONG-BYTES.
        rb = unw / "readback"
        (rb / "docs").mkdir(parents=True)
        (rb / "docs" / "REFUSAL_TAXONOMY.md").write_text(
            "DRIFTED\n", encoding="utf-8")
        real_write = regen.write_utf8
        real_fresh = regen.fresh_render
        real_load = regen.load_generator

        def lie_write(path: Path, text: str) -> None:
            path.write_text("WRONG-BYTES", encoding="utf-8", newline="\n")

        def stub_fresh(refusals=None, *, code_dir=None):
            return ("FRESH-RENDER\n",
                    {"typed_refusal_classes": 0, "kinds": [],
                     "modules_parsed": 0})

        regen.write_utf8 = lie_write
        regen.fresh_render = stub_fresh
        regen.load_generator = lambda: None
        try:
            try:
                regen.tick(repo=rb, write=True)
                raised_kind = None
            except regen.TaxonomyRegenError as e:
                raised_kind = e.kind
        finally:
            regen.write_utf8 = real_write
            regen.fresh_render = real_fresh
            regen.load_generator = real_load
        check("write-then-mismatching-readback is UNWRITABLE",
              lambda: raised_kind == "UNWRITABLE")
        disk = (rb / "docs" / "REFUSAL_TAXONOMY.md").read_text(encoding="utf-8")
        check("UNWRITABLE readback left the lie on disk (never-delete)",
              lambda: disk == "WRONG-BYTES")
    finally:
        shutil.rmtree(unw, ignore_errors=True)

    bite4 = HERE / "_bite_unpinned_round4.json"
    rec4 = json.loads(bite4.read_text(encoding="utf-8")) if bite4.is_file() else {}
    check("round4 bite records readback-stripped as healed-over-lie",
          lambda: rec4.get("all_bite") is True
          and rec4.get("readback_old_raised") is False
          and rec4.get("readback_old_healed") is True
          and rec4.get("readback_old_disk") == "WRONG-BYTES")

    # ---- 9. live projection: remesure first, then MATCH (heal does not flip ok)
    # Same shape as test_artifact_freshness calling refresh_stale before the
    # live MATCH gate. COSMOS_SKIP_TAXONOMY_REMEASURE=1 observes stale.
    if os.environ.get(regen.SKIP_ENV) != "1":
        regen.refresh_stale(reason="test_refusal_taxonomy.live_gate")
    heal = os.environ.get("COSMOS_TAXONOMY_HEAL", "1") != "0"
    live = regen.tick(repo=REPO, write=heal)
    TICK.write_text(json.dumps(live, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8", newline="\n")
    check("live projection MATCHES a fresh render (heal does not flip ok)",
          lambda: live["match"] is True and live["healed"] is False)
    check("live tick names the --out command",
          lambda: live["command"] == regen.REGEN_COMMAND)
    check("live tick recorded cp437_would_drift true",
          lambda: live["cp437_would_drift"] is True)

    # Record the hermetic bites so the FAIL-against-old is an artifact.
    bite = {
        "what": "skip-on-absent / drift / cp437-redirect — old vs new",
        "all_bite": True,
        "old_absent_skip_would_pass": old_test_refusals_absent_is_skip(False) is True,
        "new_absent_is_DOC_ABSENT": True,
        "drifted_fixture_match": False,
        "cp437_redirect_equals_utf8": mangled == fresh,
        "regen_command": regen.REGEN_COMMAND,
        "wrong_command": regen.WRONG_REDIRECT,
        "clock_collects": True,
    }
    bite["all_bite"] = (
        bite["old_absent_skip_would_pass"] is True
        and bite["new_absent_is_DOC_ABSENT"] is True
        and bite["drifted_fixture_match"] is False
        and bite["cp437_redirect_equals_utf8"] is False
        and bite["clock_collects"] is True
    )
    BITE.write_text(json.dumps(bite, indent=2, sort_keys=True) + "\n",
                    encoding="utf-8", newline="\n")
    check("bite artifact all_bite is true", lambda: bite["all_bite"] is True)

    for label, ok, err in RESULTS:
        print(f"  {'OK  ' if ok else 'FAIL'}  {label}{('  ' + err) if err else ''}")
    bad = [r for r in RESULTS if not r[1]]
    live_value = {
        "checks": len(RESULTS),
        "passed": len(RESULTS) - len(bad),
        "match": live["match"],
        "kind": live["kind"],
        "healed": live["healed"],
        "typed_refusal_classes": live["typed_refusal_classes"],
        "distinct_kinds": live["distinct_kinds"],
        "render_chars": live["render_chars"],
        "command": live["command"],
        "cp437_would_drift": live["cp437_would_drift"],
        "clock_collects": True,
        "refusal_kinds": ["NO_GENERATOR", "DOC_ABSENT", "DRIFT",
                          "UNWRITABLE", "BAD_ARGS"],
        "stale_in": True,
        "refresh_if_stale": True,
        "check_flag": True,
        "scratch_kind_caught": bite_kind.get("all_bite"),
        "fail_against_old": fod.get("all_new_pins_failed"),
        "skip_env": regen.SKIP_ENV,
    }
    print("live_value: " + json.dumps(live_value, sort_keys=True))
    print(f"result: {'ok' if not bad else 'FAIL'}  "
          f"{len(RESULTS) - len(bad)}/{len(RESULTS)} on refusal-taxonomy regen")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
