#!/usr/bin/env python3
"""Validate figure SEO outputs for the Mission furniture deep pack."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent
DRAFTS = ROOT / "drafts"
FIGURES = ROOT / "figures"
REGISTRY = FIGURES / "registry.json"
RIGHTS = ROOT / "RIGHTS.md"

ALLOWED_HOSTS = {
    "images.metmuseum.org",
    "upload.wikimedia.org",
    "loc.gov",
    "tile.loc.gov",
    "cdn.loc.gov",
    "ids.si.edu",
}

BANNED_IMG = re.compile(r"(midjourney|dall-e|openai\.com/.*image|stable.?diffusion|generated by ai)", re.I)


def parse_slug_chapter(path: Path) -> tuple[str, int]:
    text = path.read_text(encoding="utf-8")
    parts = re.split(r"^---\s*$", text, flags=re.M)
    fm = parts[1] if len(parts) > 2 else ""
    slug = re.search(r"^slug:\s*(\S+)", fm, re.M)
    ch = re.search(r"^chapter:\s*0*(\d+)", fm, re.M)
    return (slug.group(1) if slug else path.stem, int(ch.group(1)) if ch else 0)


def count_figs_in_draft(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    return len(re.findall(r"\*\*Fig\.", text))


def main() -> int:
    errors: list[str] = []
    if not REGISTRY.is_file():
        errors.append("missing figures/registry.json — run build_figure_seo.py")
    if not RIGHTS.is_file():
        errors.append("missing RIGHTS.md — run build_figure_seo.py")
    if errors:
        for e in errors:
            print(f"  - {e}")
        return 1

    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    if not reg.get("no_ai_images"):
        errors.append("registry.json: no_ai_images must be true")
    fig_rows = reg.get("figures") or []
    by_slug: dict[str, list] = {}
    for row in fig_rows:
        by_slug.setdefault(row["slug"], []).append(row)

    for path in sorted(DRAFTS.glob("*.md")):
        slug, _ch = parse_slug_chapter(path)
        n_draft = count_figs_in_draft(path)
        html_path = FIGURES / f"{slug}.figures.html"
        if not html_path.is_file():
            errors.append(f"{slug}: missing {html_path.name}")
            continue
        html = html_path.read_text(encoding="utf-8")
        n_fig = len(re.findall(r"<figure\b", html))
        if n_fig != n_draft:
            errors.append(f"{slug}: draft has {n_draft} figs, html has {n_fig}")
        reg_slug = by_slug.get(slug, [])
        if len(reg_slug) != n_draft:
            errors.append(f"{slug}: registry count {len(reg_slug)} != draft {n_draft}")
        for img_m in re.finditer(r'<img\s+[^>]*src="([^"]+)"', html):
            src = img_m.group(1)
            if BANNED_IMG.search(src):
                errors.append(f"{slug}: banned AI-like image URL {src[:60]}")
            host = urlparse(src).hostname or ""
            if host not in ALLOWED_HOSTS:
                errors.append(f"{slug}: img host not allowlisted: {host}")
        for fig_m in re.finditer(r"<figure\b[^>]*>", html):
            tag = fig_m.group(0)
            if "data-import=" not in tag:
                errors.append(f"{slug}: figure missing data-import")
        if "<figure" in html and 'alt=""' in html:
            errors.append(f"{slug}: empty alt on img")

    if not (ROOT / "IMAGE_SEO.md").is_file():
        errors.append("missing IMAGE_SEO.md")

    print(f"registry figures: {len(fig_rows)}")
    hotlink = sum(1 for r in fig_rows if r.get("import_status") == "hotlink_ok")
    print(f"hotlink_ok: {hotlink}")
    if errors:
        print("FAIL")
        for e in errors:
            print(f"  - {e}")
        return 1
    print("PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
