#!/usr/bin/env python3
"""Editorial pack data for millwork-molding-history (BBF lane)."""

from __future__ import annotations

PACK = "millwork-molding-history"
LANE = "bbf-millwork"
GRAPHICS_AGENT = "v1"

# First two H2 titles are a graphics contract. Do not rename after assets land.
ARTICLES: list[dict] = [
    {
        "n": 1,
        "slug": "what-millwork-is",
        "file": "01-what-millwork-is.md",
        "title": "What millwork is, and what it is not",
        "era_focus": "shop language, 19th c.–now",
        "meta": "Millwork is shaped wood made to a profile and a length. It is not a sawmill, not a millwright, and not furniture until someone cuts a joint.",
        "tags": ["definition", "shop", "bbf"],
        "h2": ["Three words that get borrowed", "A stick, a profile, a length"],
        "anchors": [
            ("c. 1820", "American pattern books name mouldings"),
            ("1870s", "Heavy inside moulders enter U.S. shops"),
            ("1903", "Warren hardwood mills at full cut"),
            ("now", "Sticker line and CNC share one ticket"),
        ],
        "plate": "words",
        "citations": [
            "Asher Benjamin, The American Builder's Companion (Boston, 6th ed. 1827).",
            "C. R. Tompkins, A History of the Planing-Mill (New York, 1889).",
            "Encyclopedia of Arkansas, “Bradley County.”",
        ],
    },
    {
        "n": 2,
        "slug": "eight-regular-moldings",
        "file": "02-eight-regular-moldings.md",
        "title": "The eight regular moldings, as a shop grammar",
        "era_focus": "classical → Asher Benjamin 1827",
        "meta": "Benjamin numbered eight regular mouldings and gave each a job: support, shelter, bind, or separate. The catalog number is not the grammar.",
        "tags": ["benjamin", "profiles", "grammar"],
        "h2": ["Benjamin’s eight, and why they have jobs", "A plate of eight sections"],
        "anchors": [
            ("antiquity", "Roman and Greek sections named"),
            ("1570", "Palladio’s Four Books in print"),
            ("1827", "Benjamin’s sixth Companion edition"),
            ("now", "Stock knives still chase the eight"),
        ],
        "plate": "eight",
        "citations": [
            "Asher Benjamin, The American Builder's Companion (1827), on regular mouldings.",
            "R. G. Hatfield, The American House Carpenter, § mouldings.",
            "Andrea Palladio, I quattro libri dell'architettura (Venice, 1570).",
        ],
    },
    {
        "n": 3,
        "slug": "greek-vs-roman-profiles",
        "file": "03-greek-vs-roman-profiles.md",
        "title": "Greek curves against Roman circles",
        "era_focus": "1762–1850s Greek Revival",
        "meta": "Roman mouldings are single-radius arcs. Greek ones take ellipses and quirks. Stuart and Revett made that a shop problem, not a museum one.",
        "tags": ["greek", "roman", "quirk"],
        "h2": ["When the books changed the knives", "Quirked ovolo against a quarter-round"],
        "anchors": [
            ("1570", "Palladio draws Roman circles"),
            ("1762", "Stuart & Revett, Antiquities of Athens vol. 1"),
            ("1806", "Benjamin prefers the quirked ovolo"),
            ("c. 1900", "Colonial Revival puts Roman back"),
        ],
        "plate": "greek_roman",
        "citations": [
            "Calder Loth, “Notes on Moldings, the change from Roman to Greek,” ICAA (2015).",
            "James Stuart and Nicholas Revett, The Antiquities of Athens, vol. 1 (London, 1762).",
            "Asher Benjamin, The American Builder's Companion (1806; 1827).",
        ],
    },
    {
        "n": 4,
        "slug": "egyptian-cavetto-gorge",
        "file": "04-egyptian-cavetto-gorge.md",
        "title": "The Egyptian cavetto and the gorge cornice",
        "era_focus": "pharaonic → 19th c. Egyptian Revival",
        "meta": "The big hollow that throws water off a temple wall is older than a Grecian ovolo. Shops still steal the gorge when a room wants a hard shadow.",
        "tags": ["egypt", "cavetto", "revival"],
        "h2": ["A hollow older than the orders", "Gorge against a small cove"],
        "anchors": [
            ("pharaonic", "Cavetto cornice on temple walls"),
            ("1798", "Napoleon’s Description de l’Égypte begins"),
            ("1830s", "Egyptian Revival interiors in the U.S."),
            ("now", "Stock cove is not a gorge"),
        ],
        "plate": "gorge",
        "citations": [
            "1911 Encyclopaedia Britannica, “Mouldings,” on Egyptian cavetto.",
            "Description de l’Égypte (Paris, from 1809).",
            "Asher Benjamin, on cavetto as a covering member (1827).",
        ],
    },
    {
        "n": 5,
        "slug": "gothic-medieval-moldings",
        "file": "05-gothic-medieval-moldings.md",
        "title": "Gothic hollows and the medieval section",
        "era_focus": "12th–15th c.; Gothic Revival 19th c.",
        "meta": "Medieval mouldings chase light down a hollow, not around a Roman circle. A Victorian Gothic knife is a revival of that chase, not a Tuscan leftover.",
        "tags": ["gothic", "medieval", "revival"],
        "h2": ["Hollows that swallow light", "A roll, a hollow, a fillet"],
        "anchors": [
            ("12th c.", "Early Gothic roll mouldings"),
            ("14th c.", "Deep hollows and wave mouldings"),
            ("1840s", "Pugin and the English Gothic Revival"),
            ("1870s", "U.S. catalogs sell Gothic stock"),
        ],
        "plate": "gothic",
        "citations": [
            "1911 Encyclopaedia Britannica, “Mouldings,” Gothic section.",
            "A. W. N. Pugin, The True Principles of Pointed or Christian Architecture (London, 1841).",
            "James Newlands, The Carpenter’s Assistant (mid-19th c.).",
        ],
    },
    {
        "n": 6,
        "slug": "vignola-palladio-rulebooks",
        "file": "06-vignola-palladio-rulebooks.md",
        "title": "Vignola, Palladio, and the Renaissance rule books",
        "era_focus": "1550–1700",
        "meta": "Italian treatises made moulding a measured language. American shops inherited that language through English plates, not through a trip to Vicenza.",
        "tags": ["palladio", "vignola", "treatise"],
        "h2": ["Who wrote the shop’s Latin", "Tuscan cornice as three jobs"],
        "anchors": [
            ("1562", "Vignola, Regola delli cinque ordini"),
            ("1570", "Palladio, Four Books"),
            ("1615", "Scamozzi’s L'idea"),
            ("1738", "Ware’s English Palladio"),
        ],
        "plate": "tuscan_cornice",
        "citations": [
            "Giacomo Barozzi da Vignola, Regola delli cinque ordini d'architettura (1562).",
            "Andrea Palladio, I quattro libri dell'architettura (1570).",
            "Isaac Ware, The Four Books of Andrea Palladio's Architecture (London, 1738).",
        ],
    },
    {
        "n": 7,
        "slug": "gibbs-swan-anglo-palladian",
        "file": "07-gibbs-swan-anglo-palladian.md",
        "title": "Gibbs, Swan, and the Anglo-Palladian shop",
        "era_focus": "1720s–1760s",
        "meta": "English plates taught colonial joiners how to size a cornice before anyone in Boston had seen the Parthenon. Gibbs still sizes rooms.",
        "tags": ["gibbs", "swan", "georgian"],
        "h2": ["English plates in American tool chests", "Gibbs cornice fractions"],
        "anchors": [
            ("1732", "Gibbs, Rules for Drawing"),
            ("1745", "Abraham Swan, The British Architect"),
            ("1738", "Salmon, Palladio Londinensis"),
            ("c. 1750", "Drayton Hall mantel follows Roman rules"),
        ],
        "plate": "gibbs",
        "citations": [
            "James Gibbs, Rules for Drawing the Several Parts of Architecture (London, 1732).",
            "Abraham Swan, The British Architect (1745).",
            "Calder Loth, ICAA, on Drayton Hall and Palladio Londinensis.",
        ],
    },
    {
        "n": 8,
        "slug": "stuart-revett-greek-turn",
        "file": "08-stuart-revett-greek-turn.md",
        "title": "Stuart, Revett, and the 1762 Greek turn",
        "era_focus": "1751–1830",
        "meta": "The Antiquities of Athens did not stay in libraries. Adam bent the curves. American Greek Revival shops had to grind new irons.",
        "tags": ["stuart", "revett", "adam"],
        "h2": ["A book that changed a plane iron", "Ilissus quirk against a Roman abacus"],
        "anchors": [
            ("1751", "Stuart and Revett reach Athens"),
            ("1758", "Le Roy’s Ruines des plus beaux monuments"),
            ("1762", "Antiquities of Athens, vol. 1"),
            ("1778", "Adam, Works in Architecture, vol. 1"),
        ],
        "plate": "ilissus",
        "citations": [
            "Stuart and Revett, The Antiquities of Athens, vol. 1 (1762).",
            "Robert and James Adam, The Works in Architecture, vol. 1 (1778).",
            "Julien-David Le Roy, Ruines des plus beaux monuments de la Grèce (1758).",
        ],
    },
    {
        "n": 9,
        "slug": "asher-benjamin-companion",
        "file": "09-asher-benjamin-companion.md",
        "title": "Asher Benjamin and the American country shop",
        "era_focus": "1797–1845",
        "meta": "Benjamin taught country builders to strike regular and quirked mouldings from copperplates. The Companion is still the honest American millwork book.",
        "tags": ["benjamin", "america", "pattern-book"],
        "h2": ["Greenfield plates for a wooden republic", "The 45-degree cornice experiment"],
        "anchors": [
            ("1797", "Country Builder’s Assistant"),
            ("1806", "American Builder’s Companion, 1st ed."),
            ("1827", "Sixth edition, 70 plates"),
            ("1833", "Lafever cites Stuart & Revett"),
        ],
        "plate": "benjamin_exp",
        "citations": [
            "Asher Benjamin, The Country Builder's Assistant (Greenfield, 1797/1805).",
            "Asher Benjamin, The American Builder's Companion (1806; 6th ed. 1827).",
            "Minard Lafever, The Modern Builder's Guide (1833).",
        ],
    },
    {
        "n": 10,
        "slug": "lafever-greek-revival-plane",
        "file": "10-lafever-greek-revival-plane.md",
        "title": "Lafever, the arris, and the Greek Revival plane",
        "era_focus": "1820–1860",
        "meta": "Minard Lafever borrowed Athens and handed American carpenters a sharper iron. Rural mantels stacked quirked ovolos until the wall looked like a Doric echinus.",
        "tags": ["lafever", "greek-revival", "plane"],
        "h2": ["New York plates, country houses", "Stacked arrises under a shelf"],
        "anchors": [
            ("1833", "Lafever, Modern Builder’s Guide"),
            ("1831", "Glen Maury mantel, Buena Vista, Va."),
            ("1840s", "Annandale shelf, Buckingham County"),
            ("1859", "Strickland’s Tennessee Capitol interiors"),
        ],
        "plate": "arris",
        "citations": [
            "Minard Lafever, The Modern Builder's Guide (New York, 1833).",
            "Calder Loth, ICAA, on Glen Maury and Annandale mantels.",
            "William Strickland, Tennessee State Capitol (completed 1859).",
        ],
    },
    {
        "n": 11,
        "slug": "victorian-stock-catalogs",
        "file": "11-victorian-stock-catalogs.md",
        "title": "Victorian catalogs and the stock stick",
        "era_focus": "1860–1900",
        "meta": "Steam planing mills made a profile a catalog number. The stick got cheaper. The shadow got thinner unless someone still built the cornice in three parts.",
        "tags": ["victorian", "catalog", "steam"],
        "h2": ["When a profile became a SKU", "Catalog crown against a built-up"],
        "anchors": [
            ("1850s", "Woodworth planer in wide use"),
            ("1870", "Heavy moulding machines advertised"),
            ("1889", "Tompkins writes the planing-mill history"),
            ("1890s", "Mail-order millwork to the prairie"),
        ],
        "plate": "catalog",
        "citations": [
            "C. R. Tompkins, A History of the Planing-Mill (1889).",
            "VintageMachinery.org, short history of moulding machines.",
            "William Woodworth planer patent lineage (1828 and after).",
        ],
    },
    {
        "n": 12,
        "slug": "colonial-revival-roman-return",
        "file": "12-colonial-revival-roman-return.md",
        "title": "Colonial Revival and the return of Roman curves",
        "era_focus": "1880–1940",
        "meta": "The twentieth century put Roman quarter-rounds back on American doors. Greek quirks looked old-fashioned. The shop ground simpler knives and called it taste.",
        "tags": ["colonial-revival", "roman", "20th-c"],
        "h2": ["A fashion that flattened the quirk", "Revival casing against a Greek door"],
        "anchors": [
            ("1876", "Centennial Exhibition taste"),
            ("1890s", "McKim, Mead & White interiors"),
            ("1920s", "Catalog Colonial millwork"),
            ("1935", "Warren, Ark., Colonial Revival post office"),
        ],
        "plate": "revival_casing",
        "citations": [
            "Calder Loth, ICAA, on Colonial Revival and Roman mouldings.",
            "Rachel Silva, Historic Downtown Warren tour script (AHPP, 2012).",
            "McKim, Mead & White domestic interiors, 1880s–1910s.",
        ],
    },
    {
        "n": 13,
        "slug": "southern-mill-towns-planer",
        "file": "13-southern-mill-towns-planer.md",
        "title": "Southern mill towns and the planer mill",
        "era_focus": "1880–1958",
        "meta": "Yellow pine and bottomland oak paid for whole towns. The planer mill sat next to the saw. Millwork left those sheds as flooring, furniture stock, and pine trim.",
        "tags": ["south", "planer", "mill-town"],
        "h2": ["A town built on a daily cut", "From log deck to sticker shed"],
        "anchors": [
            ("1882", "Lindsay & Ainsworth operation, later Southern Lumber"),
            ("1901–02", "Warren’s three big mills incorporate"),
            ("1907", "100,000 bf/day class shops"),
            ("1956–58", "Potlatch buys Southern and Bradley"),
        ],
        "plate": "mill_flow",
        "citations": [
            "Encyclopedia of Arkansas, “Bradley County.”",
            "Rex Nelson, “Pine trees, pink tomatoes,” Arkansas Democrat-Gazette (2026).",
            "argenweb.net, Bradley Lumber Company postcard text.",
        ],
    },
    {
        "n": 14,
        "slug": "bradley-county-hardwood-belt",
        "file": "14-bradley-county-hardwood-belt.md",
        "title": "Bradley County in the hardwood belt",
        "era_focus": "1901–present",
        "meta": "Warren cut oak and mild-textured hardwoods while the pine belt roared next door. BBF millwork still lives in that split: furniture stock, flooring, and linear trim.",
        "tags": ["bradley", "warren", "bbf"],
        "h2": ["Three mills and a doubled town", "Oak, pine, and what a shop still buys"],
        "anchors": [
            ("1901", "Bradley Lumber incorporated by S. H. Fullerton"),
            ("1903", "Mill open; later BBF furniture date-line"),
            ("1928", "Arkansas Lumber cuts out"),
            ("2008", "Hardwood sawmill strain in the state"),
        ],
        "plate": "species_belt",
        "citations": [
            "Encyclopedia of Arkansas, “Bradley County.”",
            "Bradley Lumber postcard: oak, pine millwork, furniture stock.",
            "Arkansas Democrat-Gazette, hardwood mill strain, 30 Nov 2008.",
        ],
    },
    {
        "n": 15,
        "slug": "four-side-moulder-history",
        "file": "15-four-side-moulder-history.md",
        "title": "The four-side moulder, from sticker to Unimat",
        "era_focus": "1848–1980s",
        "meta": "A sticker made a stick. A four-side moulder made a living. Fox, Fay, Rogers, Woods, then Weinig. The knife still has to be as true as the story.",
        "tags": ["moulder", "weinig", "machinery"],
        "h2": ["American stickers, then German series", "Four heads around one stick"],
        "anchors": [
            ("1848", "C. B. Rogers at Norwich"),
            ("1870", "Heavy moulders (Fay & Fisher lineage)"),
            ("1964", "Weinig specializes in moulders"),
            ("1970", "Weinig line assembly, Unimat era"),
        ],
        "plate": "four_head",
        "citations": [
            "VintageMachinery.org, short history of moulding machines.",
            "WOOD TEC PEDIA, moulder history notes (Guilliet, Wadkin, Weinig).",
            "Weinig company history; 35,000th moulder coverage (2013).",
        ],
    },
    {
        "n": 16,
        "slug": "postwar-ranch-skinny-crown",
        "file": "16-postwar-ranch-skinny-crown.md",
        "title": "The ranch house and the skinny crown",
        "era_focus": "1945–1975",
        "meta": "Eight-foot plate and a 2-1/4 sprung crown taught a generation that trim is optional. The shadow left the room. Getting it back is a proportion job.",
        "tags": ["ranch", "postwar", "crown"],
        "h2": ["A ceiling that refused an order", "Skinny sprung crown against a built-up"],
        "anchors": [
            ("1940s", "FHA minimums and the 8-foot plate"),
            ("1950s", "Ranch plan books drop the cornice"),
            ("1960s", "Finger-joint paint-grade everywhere"),
            ("1970s", "Colonial appliqué on the same box"),
        ],
        "plate": "skinny",
        "citations": [
            "Classical Proportions, cornice sizing from Gibbs (interior methods).",
            "William Chambers, Treatise on Civil Architecture, interior cornice bounds.",
            "U.S. postwar tract-house millwork practice (shop memory; [VERIFY] local code year).",
        ],
    },
    {
        "n": 17,
        "slug": "finger-joint-mdf-paint-grade",
        "file": "17-finger-joint-mdf-paint-grade.md",
        "title": "Finger-joint, MDF, and the paint-grade century",
        "era_focus": "1960–present",
        "meta": "Paint-grade is a finish decision that became a material. Finger-joint pine and MDF hold a profile. They do not hold a stain story, and they move differently in the South.",
        "tags": ["paint-grade", "mdf", "finger-joint"],
        "h2": ["Why the joint disappeared under primer", "Solid, finger-joint, and a painted MDF"],
        "anchors": [
            ("1960s", "Finger-joint trim in merchant yards"),
            ("1980s", "MDF moulding lines scale up"),
            ("1990s", "Primed FJ becomes the default stick"),
            ("now", "Stain-grade is a special order again"),
        ],
        "plate": "materials",
        "citations": [
            "AWI Architectural Woodwork Standards, paint- vs stain-grade notes.",
            "WMMPA / industry practice on primed finger-joint moulding.",
            "Southern humidity and MDF swelling — shop practice, not a lab paper.",
        ],
    },
    {
        "n": 18,
        "slug": "cnc-vs-sticker-line",
        "file": "18-cnc-vs-sticker-line.md",
        "title": "CNC parts against the sticker line",
        "era_focus": "1990s–present",
        "meta": "A router can carve a newel. It is a slow way to make 400 feet of base. Linear millwork still belongs on a moulder. The ticket has to say which.",
        "tags": ["cnc", "sticker", "workflow"],
        "h2": ["Two machines, two kinds of money", "A part versus a stick"],
        "anchors": [
            ("1990s", "CNC routers enter custom shops"),
            ("2000s", "Nested-base cabinets crowd the floor"),
            ("2010s", "Custom knives still beat a bit for footage"),
            ("now", "BBF-style shops run both on one job"),
        ],
        "plate": "cnc_vs",
        "citations": [
            "Shop practice: linear moulder vs CNC cycle time (internal BBF lane).",
            "Weinig / industrial moulder feed-rate literature.",
            "AWI, custom architectural woodwork vs stock millwork.",
        ],
    },
    {
        "n": 19,
        "slug": "healthcare-hospitality-millwork",
        "file": "19-healthcare-hospitality-millwork.md",
        "title": "Healthcare and hospitality millwork, as a shop lane",
        "era_focus": "1990s–present",
        "meta": "SNF corridors and hotel casework taught a hardwood shop to think about cleanability, ADA clearances, and a finish that survives a night shift. That is still millwork.",
        "tags": ["healthcare", "hospitality", "bbf"],
        "h2": ["FF&E that has to take a gurney", "A cleanable edge against a dust ledge"],
        "anchors": [
            ("1990", "ADA as a daily shop constraint"),
            ("2000s", "Hotel and SNF casework packages"),
            ("2010s", "Solid surface and hardwood share rooms"),
            ("now", "Same shop language, harder spec"),
        ],
        "plate": "clean_edge",
        "citations": [
            "ADA Standards for Accessible Design (2010), clearances that move casework.",
            "AWI / WI healthcare woodwork notes (cleanability, edges).",
            "BBF lane: healthcare and hospitality FF&E as a millwork customer, not a brochure.",
        ],
    },
    {
        "n": 20,
        "slug": "reading-a-room-as-an-order",
        "file": "20-reading-a-room-as-an-order.md",
        "title": "Reading a room as if it still had an order",
        "era_focus": "classical method, any job",
        "meta": "Base is a pedestal. Chair rail is a dado cap. Casing is an architrave. Crown is a cornice. If you skip that map, the sticks fight each other.",
        "tags": ["orders", "proportion", "rooms"],
        "h2": ["The wall is still a temple, cheaply", "Pedestal, column, entablature on drywall"],
        "anchors": [
            ("classical", "Entablature on a wall"),
            ("1732", "Gibbs sizes the interior cornice"),
            ("1827", "Benjamin on profiles as assemblies"),
            ("now", "Stock rooms still obey or fail the map"),
        ],
        "plate": "room_order",
        "citations": [
            "Mouldings One / ICAA teaching: architrave, dado, cornice on a wall.",
            "James Gibbs, Rules for Drawing (1732).",
            "Classical Proportions, cornice methods 1–3.",
        ],
    },
    {
        "n": 21,
        "slug": "cyma-recta-cymatium",
        "file": "21-cyma-recta-cymatium.md",
        "title": "Cyma recta: the wave that wants to be a gutter",
        "era_focus": "classical → shop crown",
        "meta": "Cyma recta is concave then convex as it falls. It sheds water on a building and finishes a cornice in a room. Reverse it and you have a different job.",
        "tags": ["cyma", "crown", "profile"],
        "h2": ["A wave with a weather job", "Recta against reversa"],
        "anchors": [
            ("classical", "Cymatium as the cornice’s top"),
            ("1827", "Benjamin: covering, not supporting"),
            ("Victorian", "Anthemion on the cyma"),
            ("now", "One-piece crown still starts here"),
        ],
        "plate": "cyma_pair",
        "citations": [
            "1911 Encyclopaedia Britannica, “Mouldings,” cyma recta / cymatium.",
            "Asher Benjamin, covering members (1827).",
            "Classical Proportions, cyma–corona–bedmould.",
        ],
    },
    {
        "n": 22,
        "slug": "cyma-reversa-ogee",
        "file": "22-cyma-reversa-ogee.md",
        "title": "Cyma reversa, or the ogee that can hold weight",
        "era_focus": "classical → door and bedmould",
        "meta": "Ogee is convex then concave as it falls. Benjamin called it strong at the ends. That is why it sits under a corona and on a door cap.",
        "tags": ["ogee", "cyma-reversa", "support"],
        "h2": ["The support wave", "Quirked ogee and a plain talon"],
        "anchors": [
            ("classical", "Cyma reversa / French talon"),
            ("1827", "Benjamin: fit for supports"),
            ("Greek", "Quirked ogee in plates"),
            ("now", "Door cap and bedmould still use it"),
        ],
        "plate": "ogee",
        "citations": [
            "Asher Benjamin, ovolo and ogee as supports (1827).",
            "1911 Britannica, cyma-reversa / ogee.",
            "Jane Griswold Radocchia on Benjamin and falling water (2009).",
        ],
    },
    {
        "n": 23,
        "slug": "ovolo-echinus-quirk",
        "file": "23-ovolo-echinus-quirk.md",
        "title": "Ovolo, echinus, and the quirk that makes a line",
        "era_focus": "Greek and Roman",
        "meta": "A Roman ovolo is a quarter circle. A Greek echinus leans and quirks. The dark hairline at the quirk is the whole point. Lose it and you have a blob.",
        "tags": ["ovolo", "quirk", "echinus"],
        "h2": ["Egg, quarter-round, and a hairline", "Three ovolos in one height"],
        "anchors": [
            ("Roman", "Single-radius quarter-round"),
            ("Greek", "Elliptical echinus with quirk"),
            ("1806", "Benjamin’s ovolo experiment"),
            ("now", "Router quarter-round is not an echinus"),
        ],
        "plate": "ovolo3",
        "citations": [
            "Asher Benjamin, 1806/1827 ovolo experiment.",
            "Calder Loth, quirked ovolo definition (ICAA).",
            "1911 Britannica, ovolo / echinus.",
        ],
    },
    {
        "n": 24,
        "slug": "cavetto-cove",
        "file": "24-cavetto-cove.md",
        "title": "Cavetto and cove: the hollow that covers",
        "era_focus": "classical → sprung cove",
        "meta": "Cavetto is a quarter hollow. It covers; it does not hold. A sprung cove in a ranch house is the same idea with the corona stripped out.",
        "tags": ["cavetto", "cove", "covering"],
        "h2": ["A point that must not carry", "Cove sprung, cove built"],
        "anchors": [
            ("classical", "Cavetto as covering member"),
            ("Egyptian", "Large gorge cavetto"),
            ("Victorian", "Scotia standing in for corona"),
            ("1950s", "Sprung cove as the cheap cornice"),
        ],
        "plate": "cavetto",
        "citations": [
            "Asher Benjamin, cavetto as covering (1827).",
            "Classical Proportions, Victorian scotia variation.",
            "1911 Britannica, cavetto.",
        ],
    },
    {
        "n": 25,
        "slug": "torus-astragal-bead",
        "file": "25-torus-astragal-bead.md",
        "title": "Torus, astragal, bead: the ropes",
        "era_focus": "classical bases and necking",
        "meta": "Half-rounds bind. A torus is the fat rope at a column base. An astragal is the thin one. A bead on a door is the same thought at cabinet scale.",
        "tags": ["torus", "astragal", "bead"],
        "h2": ["Ropes that pretend to hold the work together", "Torus, astragal, and a stuck bead"],
        "anchors": [
            ("classical", "Torus at the base, astragal at the neck"),
            ("Greek", "Bead-and-reel on the astragal"),
            ("shop", "Stuck bead vs applied panel mould"),
            ("now", "Router bead bits flatten the rope"),
        ],
        "plate": "ropes",
        "citations": [
            "Asher Benjamin, torus and astragal as binding members.",
            "1911 Britannica, torus, astragal, bead-and-reel.",
            "Hatfield, American House Carpenter, bead/astragal.",
        ],
    },
    {
        "n": 26,
        "slug": "scotia-dark-hollow",
        "file": "26-scotia-dark-hollow.md",
        "title": "Scotia: the hollow named for darkness",
        "era_focus": "classical bases",
        "meta": "Scotia sits under a torus so the eye gets a black line. The word is darkness. If you fill it with a timid cove, the base goes gray.",
        "tags": ["scotia", "base", "shadow"],
        "h2": ["Why the hollow is supposed to go black", "Attic base in three moves"],
        "anchors": [
            ("Greek", "Attic base: torus, scotia, torus"),
            ("etymology", "skotia, darkness"),
            ("1827", "Benjamin: separate and contrast"),
            ("now", "Shoe mould pretending to be a scotia"),
        ],
        "plate": "attic_base",
        "citations": [
            "1911 Britannica, scotia / trochilus.",
            "Asher Benjamin, fillet and scotia as separators (1827).",
            "Vignola / Gibbs plates of the Attic base.",
        ],
    },
    {
        "n": 27,
        "slug": "fillet-fascia-corona",
        "file": "27-fillet-fascia-corona.md",
        "title": "Fillet, fascia, corona: the flats that make shade",
        "era_focus": "classical cornice",
        "meta": "Curves get the names. Flats do the work. A corona without a soffit is how cheap crown loses its crown.",
        "tags": ["fillet", "corona", "fascia"],
        "h2": ["The members nobody puts on a T-shirt", "Corona with a soffit, and without"],
        "anchors": [
            ("classical", "Corona as the eave slab"),
            ("etymology", "Crown moulding from corona"),
            ("Victorian", "Flattened corona to lift a ceiling"),
            ("now", "One-piece crown with no soffit"),
        ],
        "plate": "corona",
        "citations": [
            "Classical Proportions, corona / soffit / crown etymology.",
            "Asher Benjamin, fillet as separator.",
            "Gibbs, Tuscan cornice plates.",
        ],
    },
    {
        "n": 28,
        "slug": "built-up-crown-three-parts",
        "file": "28-built-up-crown-three-parts.md",
        "title": "Built-up crown: cyma, corona, bedmould",
        "era_focus": "shop practice, any century",
        "meta": "A real interior cornice is three jobs stacked. One stick can fake two of them. It cannot fake the soffit line unless you give it a corona.",
        "tags": ["crown", "built-up", "shop"],
        "h2": ["Keep the order even when you cheapen the sticks", "Three sticks, one shadow"],
        "anchors": [
            ("classical", "Cyma–corona–bedmould"),
            ("Georgian", "Heavier interior cornices"),
            ("Victorian", "Smaller cornices, still three parts"),
            ("now", "Built-up from stock knives"),
        ],
        "plate": "built_up",
        "citations": [
            "Classical Proportions, three-part cornice.",
            "James Gibbs, order cornices.",
            "Shop practice: stacking stock WM / custom knives.",
        ],
    },
    {
        "n": 29,
        "slug": "base-plinth-shoe",
        "file": "29-base-plinth-shoe.md",
        "title": "Base, plinth, and the shoe that hides the sin",
        "era_focus": "shop practice",
        "meta": "A base is a pedestal die. A plinth is the block under it. A shoe is the apology at the floor. Mix them and the wall looks like it grew a mopboard.",
        "tags": ["base", "plinth", "shoe"],
        "h2": ["What the floor is allowed to do", "Two-piece base against a one-piece"],
        "anchors": [
            ("classical", "Pedestal plinth and die"),
            ("19th c.", "Two-piece base common"),
            ("ranch", "Skimpy one-piece mopboard"),
            ("now", "Shoe as scribe, not as profile"),
        ],
        "plate": "base",
        "citations": [
            "Mouldings One / ICAA, base as pedestal.",
            "AWI, standing and running trim.",
            "Shop practice: shoe as floor scribe.",
        ],
    },
    {
        "n": 30,
        "slug": "casing-as-architrave",
        "file": "30-casing-as-architrave.md",
        "title": "Casing is an architrave that learned to wrap a jamb",
        "era_focus": "classical → door shop",
        "meta": "The header over a door is still an architrave. Plinth blocks, backband, and a reveal are how a shop keeps that sentence from mumbling.",
        "tags": ["casing", "architrave", "doors"],
        "h2": ["A door that remembers a beam", "Three casings and a reveal"],
        "anchors": [
            ("classical", "Architrave as the beam"),
            ("Federal", "Stepped architrave casings"),
            ("Greek Revival", "Heavy eared casings"),
            ("ranch", "Clamshell and a 1/8 reveal if you are lucky"),
        ],
        "plate": "casing",
        "citations": [
            "Mouldings One, casing as architrave.",
            "Asher Benjamin and Lafever door plates.",
            "Shop practice: reveal, plinth, backband.",
        ],
    },
    {
        "n": 31,
        "slug": "chair-rail-picture-rail",
        "file": "31-chair-rail-picture-rail.md",
        "title": "Chair rail, picture rail, and the dado that is not a chair",
        "era_focus": "18th c.–1920s",
        "meta": "Chair rail is a dado cap that also saved wallpaper from a chair back. Picture rail is a later hanging stick. They are not the same height and not the same job.",
        "tags": ["chair-rail", "picture-rail", "dado"],
        "h2": ["Two rails, two centuries", "Dado cap against a picture mould"],
        "anchors": [
            ("18th c.", "Chair rail as dado cap"),
            ("19th c.", "High dados in parlors"),
            ("1890–1920", "Picture rail common in U.S. houses"),
            ("now", "One stick sold as both"),
        ],
        "plate": "rails",
        "citations": [
            "Mouldings One / ICAA, chair rail as dado.",
            "Period U.S. picture-rail practice, c. 1890–1930.",
            "Shop practice: chair height is not picture-rail height.",
        ],
    },
    {
        "n": 32,
        "slug": "bolection-panel-mould",
        "file": "32-bolection-panel-mould.md",
        "title": "Bolection, stuck mould, and the applied panel",
        "era_focus": "18th–19th c. panel work",
        "meta": "A bolection steps over the frame and the panel. A stuck mould is cut on the rail. An applied mould is a third stick. The 19th century switched horses.",
        "tags": ["bolection", "panel", "doors"],
        "h2": ["How a panel meets a rail", "Stuck, applied, bolection"],
        "anchors": [
            ("18th c.", "Stuck moulds and fielded panels"),
            ("1786", "Philadelphia Carpenters’ Company plates"),
            ("c. 1850", "Newlands: applied Greek moulds"),
            ("now", "MDF slab with a planted stick"),
        ],
        "plate": "panel",
        "citations": [
            "The Rules of Work of the Carpenters’ Company of Philadelphia (1786).",
            "James Newlands, The Carpenter’s Assistant.",
            "Calder Loth, ICAA, on the change in panel treatment.",
        ],
    },
    {
        "n": 33,
        "slug": "moisture-movement-cup",
        "file": "33-moisture-movement-cup.md",
        "title": "Moisture, movement, and why a stick cups",
        "era_focus": "shop practice, Southern humidity",
        "meta": "A profile is a weather report cut into wood. Rings, kiln tickets, and a June jobsite in the Delta will move a crown off the wall if you ignore them.",
        "tags": ["moisture", "cup", "south"],
        "h2": ["The kiln ticket is part of the profile", "How a sprung crown wants to cup"],
        "anchors": [
            ("shop", "6–8% interior MC target [VERIFY] job"),
            ("South", "Summer EMC can sit well above that"),
            ("machine", "Crown cut on two faces"),
            ("site", "Acclimate or watch the joints open"),
        ],
        "plate": "cup",
        "citations": [
            "Forest Products Laboratory, Wood Handbook, moisture and movement.",
            "Gene Wengert / Wood-Doctor practice on EMC.",
            "Shop practice: Southern acclimation before install.",
        ],
    },
    {
        "n": 34,
        "slug": "knife-grinding-hook",
        "file": "34-knife-grinding-hook.md",
        "title": "Knife grinding, hook, and the finish you can feel",
        "era_focus": "moulder room",
        "meta": "Two knives that differ by a thousandth make one knife do the work. Hook, shear, and side clearance are how oak stops tearing on a Monday morning.",
        "tags": ["knives", "moulder", "grind"],
        "h2": ["Balance is not a personality trait", "Hook, clearance, and a profile land"],
        "anchors": [
            ("old", "Square heads and a face grind"),
            ("now", "Corrugated rounds, chosen hook"),
            ("oak", "Lower hook, shear if you have it"),
            ("grind", "Match knives to ~0.0002 in if you can"),
        ],
        "plate": "knife",
        "citations": [
            "Dave Rankin / Woodweb, knife characteristics and shear.",
            "Rob Duve, grind angles ~23–25°, side clearance.",
            "Older jointing/balance notes, 6½ in circle, 5,000 rpm class.",
        ],
    },
    {
        "n": 35,
        "slug": "crown-spring-coping",
        "file": "35-crown-spring-coping.md",
        "title": "Spring angle, nested crown, and the cope",
        "era_focus": "finish carpentry",
        "meta": "Crown sits in a room at a spring, not flat on a saw. Cope the inside. Miter the outside. If the ceiling is a wave, the cope is the only honest joint.",
        "tags": ["crown", "cope", "spring"],
        "h2": ["Fence is the wall", "Nested 38 against nested 45"],
        "anchors": [
            ("shop", "38° and 45° springs as common stock"),
            ("cut", "Nested vs flat with compound math"),
            ("inside", "Cope after a 45 back-cut"),
            ("site", "Ceiling edge, not the whole soffit, should land"),
        ],
        "plate": "spring",
        "citations": [
            "Gary Katz / THISisCarpentry, cutting and coping crown.",
            "Common U.S. spring angles 38° / 45° (stock).",
            "Shop practice: cope inside, miter outside.",
        ],
    },
    {
        "n": 36,
        "slug": "species-paint-stain",
        "file": "36-species-paint-stain.md",
        "title": "Poplar, oak, walnut, pine: paint-grade and stain-grade",
        "era_focus": "Southern shop species",
        "meta": "Poplar takes paint and a profile. Red oak takes a stain and a tearout. Walnut is a furniture wood pretending to be trim. Pine is the old mill-town default.",
        "tags": ["species", "oak", "poplar"],
        "h2": ["What the belt actually grew", "Four species, one cyma"],
        "anchors": [
            ("poplar", "Paint-grade workhorse"),
            ("oak", "Stain-grade and a shear head"),
            ("walnut", "Shorts and furniture cousins"),
            ("SYP / soft pine", "Old millwork and new FJ"),
        ],
        "plate": "species",
        "citations": [
            "FPL Wood Handbook, shrinkage and hardness by species.",
            "Bradley Lumber postcard: mild-textured oak, Arkansas soft pine.",
            "Shop practice: paint-grade poplar vs stain-grade oak.",
        ],
    },
    {
        "n": 37,
        "slug": "reveals-plinth-backband",
        "file": "37-reveals-plinth-backband.md",
        "title": "Reveals, plinth blocks, and backband",
        "era_focus": "door and window shop",
        "meta": "A 3/16 reveal is a decision. A plinth lets base die cleanly. Backband is how a thin casing grows up without looking like a bandage.",
        "tags": ["reveal", "plinth", "backband"],
        "h2": ["The lines a room reads first", "Thin casing, then a backband"],
        "anchors": [
            ("reveal", "1/8 to 1/4 common; pick one"),
            ("plinth", "Thicker than casing, taller than base"),
            ("backband", "Federal and Greek Revival habit"),
            ("now", "Clamshell with no plinth, and it shows"),
        ],
        "plate": "plinth",
        "citations": [
            "Finish-carpentry practice: reveal consistency.",
            "Period American plinth-block door casings.",
            "Shop drawings: backband as a second knife, not caulk.",
        ],
    },
    {
        "n": 38,
        "slug": "shop-drawings-eighth-inch",
        "file": "38-shop-drawings-eighth-inch.md",
        "title": "Shop drawings and the eighth of an inch that pays",
        "era_focus": "custom millwork office",
        "meta": "A profile is a contract. If the drawing and the knife disagree, the wall wins and the shop eats the footage. Eighths are not decoration.",
        "tags": ["drawings", "tolerance", "custom"],
        "h2": ["The paper that keeps a knife honest", "A section that can be ground"],
        "anchors": [
            ("ticket", "Profile, species, finish, footage"),
            ("section", "Full-size or it is a wish"),
            ("field", "Verify openings before you grind"),
            ("change", "A revised eighth is a new knife"),
        ],
        "plate": "drawing",
        "citations": [
            "AWI, shop drawings and architectural woodwork.",
            "BBF lane: design-to-spec for linear millwork and CNC.",
            "Shop practice: field verify before grind.",
        ],
    },
    {
        "n": 39,
        "slug": "shop-finish-vs-site",
        "file": "39-shop-finish-vs-site.md",
        "title": "Shop finish against a site finish",
        "era_focus": "finishing room",
        "meta": "Conversion varnish in a booth is not a brush on a ladder. Stain-grade wants the first coats at the shop. Paint-grade can go either way if the joints are honest.",
        "tags": ["finish", "varnish", "paint"],
        "h2": ["Where the dust is allowed to live", "Booth film against a site film"],
        "anchors": [
            ("stain", "Shop stain, shop sealer"),
            ("paint", "Prime in shop, finish on site — or not"),
            ("healthcare", "Spec often names the system"),
            ("site", "Caulk is not a finish plan"),
        ],
        "plate": "finish",
        "citations": [
            "AWI finishing systems (conversion varnish, lacquer, site paint).",
            "Healthcare/hospitality finish specs as a cleanability file.",
            "Shop practice: prefinish long runs, leave end-cut touch-up.",
        ],
    },
    {
        "n": 40,
        "slug": "installation-last-operation",
        "file": "40-installation-last-operation.md",
        "title": "Installation is the last millwork operation",
        "era_focus": "jobsite",
        "meta": "A perfect stick dies in a bad scribe. Nail schedule, backing, and a cope that follows the wall are shop work that happens in someone else’s building.",
        "tags": ["install", "scribe", "jobsite"],
        "h2": ["The wall was never straight", "Nails, glue, and a confession of caulk"],
        "anchors": [
            ("layout", "Find high corners, spring the long runs"),
            ("fasten", "Into backing, not into hope"),
            ("scribe", "Base to floor, cabinet to wall"),
            ("caulk", "A hairline, not a fillet"),
        ],
        "plate": "install",
        "citations": [
            "Finish-carpentry practice: scribe vs caulk.",
            "Manufacturer crown/base install notes (nested, nail into framing).",
            "Shop practice: leave extra length for scribes on stain-grade.",
        ],
    },
    {
        "n": 41,
        "slug": "matching-historic-profiles",
        "file": "41-matching-historic-profiles.md",
        "title": "Matching a dead profile without guessing",
        "era_focus": "restoration shop",
        "meta": "Take a rubbing. Take a sawn cookie. Grind to the cookie, not to a catalog cousin. The house already voted.",
        "tags": ["restoration", "match", "knives"],
        "h2": ["A cookie is better than a memory", "Catalog cousin against the house section"],
        "anchors": [
            ("field", "Sawn section or lead-sheet rubbing"),
            ("shop", "Full-size plot, then grind"),
            ("paint", "Strip a sample or you grind the film"),
            ("run", "Make extra; the next opening will lie"),
        ],
        "plate": "match",
        "citations": [
            "Preservation practice: profile matching from a section.",
            "Custom knife shops: grind-to-sample.",
            "NPS / rehab notes on replacing wood features in kind [VERIFY] brief.",
        ],
    },
    {
        "n": 42,
        "slug": "why-cheap-crown-looks-cheap",
        "file": "42-why-cheap-crown-looks-cheap.md",
        "title": "Why cheap crown looks cheap",
        "era_focus": "stock yards, now",
        "meta": "It is not the price. It is the missing corona, the timid quirk, the height that is 1/40 of the room, and a spring that lands the whole soffit on a wavy ceiling.",
        "tags": ["crown", "stock", "proportion"],
        "h2": ["Four ways a stick loses the argument", "Stock 3-5/8 against a built-up 7"],
        "anchors": [
            ("height", "Gibbs: nearer 1/15–1/20 than 1/40"),
            ("parts", "No corona, no soffit line"),
            ("curve", "Roman blob, no quirk"),
            ("land", "Whole back kissing a bad ceiling"),
        ],
        "plate": "cheap",
        "citations": [
            "Classical Proportions / Gibbs cornice fractions.",
            "William Chambers, interior cornice 1/15 to 1/20.",
            "Shop practice: landing on the outer ceiling edge.",
        ],
    },
    {
        "n": 43,
        "slug": "stair-millwork",
        "file": "43-stair-millwork.md",
        "title": "Stair millwork: treads, skirt, and a newel that is not a post",
        "era_focus": "stair shop",
        "meta": "A stair is millwork that people put their weight on. Tread thickness, skirt profile, and a newel that can take a hand are not trim thoughts.",
        "tags": ["stair", "newel", "treads"],
        "h2": ["Parts that work like furniture and like a bridge", "Skirt, nosing, and a newel block"],
        "anchors": [
            ("tread", "Thickness and nosing as a profile"),
            ("skirt", "Open vs closed string"),
            ("newel", "Through-post vs face-mount"),
            ("code", "Guard and handrail are not suggestions"),
        ],
        "plate": "stair",
        "citations": [
            "IRC / local stair geometry [VERIFY] jurisdiction.",
            "AWI, stairs and railings.",
            "Shop practice: CNC newels, moulder nosing, site fit.",
        ],
    },
    {
        "n": 44,
        "slug": "quoting-linear-vs-each",
        "file": "44-quoting-linear-vs-each.md",
        "title": "Quoting footage against quoting each",
        "era_focus": "front office",
        "meta": "A moulder sells feet after it sells setup. A CNC sells each after it sells a program. Mix the two on one page and you will eat a knife grind.",
        "tags": ["quoting", "linear", "shop"],
        "h2": ["Setup is the first board foot", "A ticket that can be built"],
        "anchors": [
            ("setup", "Grind, joint, first-stick waste"),
            ("run", "Linear feet plus drop"),
            ("each", "CNC / stair / newel"),
            ("change", "A profile change is a new setup"),
        ],
        "plate": "quote",
        "citations": [
            "Custom millwork estimating practice (setup + waste + footage).",
            "BBF lane: linear millwork vs CNC each-pricing.",
            "Knife grind lead time as a schedule item, not a surprise.",
        ],
    },
]


def by_slug(slug: str) -> dict:
    for a in ARTICLES:
        if a["slug"] == slug:
            return a
    raise KeyError(slug)
